ALTER TABLE document_revisions
    ADD COLUMN IF NOT EXISTS file_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS file_path VARCHAR(1024),
    ADD COLUMN IF NOT EXISTS file_type VARCHAR(120),
    ADD COLUMN IF NOT EXISTS file_size BIGINT;
