UPDATE publishing_templates
SET publishing_mode = CASE UPPER(COALESCE(publishing_mode, 'COVER_ONLY'))
    WHEN 'COVER_AND_HEADER_FOOTER' THEN 'COVER_HEADER_FOOTER'
    WHEN 'BODY_HEADER_FOOTER_ONLY' THEN 'HEADER_FOOTER_ONLY'
    WHEN 'HEADER_FOOTER_ONLY' THEN 'HEADER_FOOTER_ONLY'
    WHEN 'COVER_HEADER_FOOTER' THEN 'COVER_HEADER_FOOTER'
    ELSE 'COVER_ONLY'
END;

UPDATE publishing_template_versions
SET publishing_mode = CASE UPPER(COALESCE(publishing_mode, 'COVER_ONLY'))
    WHEN 'COVER_AND_HEADER_FOOTER' THEN 'COVER_HEADER_FOOTER'
    WHEN 'BODY_HEADER_FOOTER_ONLY' THEN 'HEADER_FOOTER_ONLY'
    WHEN 'HEADER_FOOTER_ONLY' THEN 'HEADER_FOOTER_ONLY'
    WHEN 'COVER_HEADER_FOOTER' THEN 'COVER_HEADER_FOOTER'
    ELSE 'COVER_ONLY'
END;
