-- V161: Harden legacy Controlled Copy actor policies.
-- Remove permissive blank actor_code rows for ACCESS_PROFILE / WORKFLOW_ROLE / DOCUMENT_WORKFLOW_POOL
-- and re-seed explicit actor rows so existing databases converge to the new contract.

DELETE FROM workflow_action_policy_actors a
USING workflow_action_policies p
WHERE a.policy_id = p.id
  AND p.module_key = 'DOCUMENT_CONTROL'
  AND p.workflow_key = 'CONTROLLED_COPY'
  AND a.actor_code IS NULL
  AND a.actor_type IN ('ACCESS_PROFILE', 'WORKFLOW_ROLE', 'DOCUMENT_WORKFLOW_POOL');

WITH controlled_copy_policies AS (
    SELECT id, object_type, action_code
    FROM workflow_action_policies
    WHERE module_key = 'DOCUMENT_CONTROL'
      AND workflow_key = 'CONTROLLED_COPY'
      AND document_type_id IS NULL
)
INSERT INTO workflow_action_policy_actors (policy_id, actor_type, actor_code)
SELECT p.id, actors.actor_type, NULL
FROM controlled_copy_policies p
JOIN (VALUES
    ('CONTROLLED_COPY', 'REQUEST_COPY', 'DCO'),
    ('CONTROLLED_COPY', 'REQUEST_COPY', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY', 'REQUEST_COPY', 'OWNER'),
    ('CONTROLLED_COPY', 'APPROVE_REQUEST', 'DCO'),
    ('CONTROLLED_COPY', 'APPROVE_REQUEST', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY', 'REJECT_REQUEST', 'DCO'),
    ('CONTROLLED_COPY', 'REJECT_REQUEST', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY', 'PREPARE_DISTRIBUTION', 'DCO'),
    ('CONTROLLED_COPY', 'PREPARE_DISTRIBUTION', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY', 'VIEW_COPY', 'DCO'),
    ('CONTROLLED_COPY', 'VIEW_COPY', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY', 'VIEW_COPY', 'OWNER'),
    ('CONTROLLED_COPY', 'PREVIEW_FILE', 'DCO'),
    ('CONTROLLED_COPY', 'PREVIEW_FILE', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY', 'PREVIEW_FILE', 'OWNER'),
    ('CONTROLLED_COPY', 'DOWNLOAD_FILE', 'DCO'),
    ('CONTROLLED_COPY', 'DOWNLOAD_FILE', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY', 'DOWNLOAD_FILE', 'OWNER'),
    ('CONTROLLED_COPY', 'RECALL_COPY', 'DCO'),
    ('CONTROLLED_COPY', 'RECALL_COPY', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY', 'REPORT_LOST_DAMAGED', 'DCO'),
    ('CONTROLLED_COPY', 'REPORT_LOST_DAMAGED', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY', 'REPORT_LOST_DAMAGED', 'OWNER'),
    ('CONTROLLED_COPY', 'REPLACE_LOST_DAMAGED', 'DCO'),
    ('CONTROLLED_COPY', 'REPLACE_LOST_DAMAGED', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY', 'UPLOAD_EVIDENCE', 'DCO'),
    ('CONTROLLED_COPY', 'UPLOAD_EVIDENCE', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY', 'UPLOAD_EVIDENCE', 'OWNER'),
    ('CONTROLLED_COPY', 'EXPIRE_COPY', 'DCO'),
    ('CONTROLLED_COPY', 'EXPIRE_COPY', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY', 'DESTROY_COPY', 'DCO'),
    ('CONTROLLED_COPY', 'DESTROY_COPY', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY', 'CONFIRM_DESTROY', 'DCO'),
    ('CONTROLLED_COPY', 'CONFIRM_DESTROY', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY', 'CANCEL_REQUEST', 'DCO'),
    ('CONTROLLED_COPY', 'CANCEL_REQUEST', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY_BATCH', 'APPROVE_REQUEST', 'DCO'),
    ('CONTROLLED_COPY_BATCH', 'APPROVE_REQUEST', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY_BATCH', 'REJECT_REQUEST', 'DCO'),
    ('CONTROLLED_COPY_BATCH', 'REJECT_REQUEST', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY_BATCH', 'PREPARE_DISTRIBUTION', 'DCO'),
    ('CONTROLLED_COPY_BATCH', 'PREPARE_DISTRIBUTION', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY_BATCH', 'DISTRIBUTE_BATCH', 'DCO'),
    ('CONTROLLED_COPY_BATCH', 'DISTRIBUTE_BATCH', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY_BATCH', 'RECALL_BATCH', 'DCO'),
    ('CONTROLLED_COPY_BATCH', 'RECALL_BATCH', 'DOCUMENT_ADMIN'),
    ('CONTROLLED_COPY_BATCH', 'CANCEL_REQUEST', 'DCO'),
    ('CONTROLLED_COPY_BATCH', 'CANCEL_REQUEST', 'DOCUMENT_ADMIN')
) AS actors(object_type, action_code, actor_type)
ON actors.object_type = p.object_type
AND actors.action_code = p.action_code
WHERE NOT EXISTS (
    SELECT 1
    FROM workflow_action_policy_actors existing
    WHERE existing.policy_id = p.id
      AND existing.actor_type = actors.actor_type
      AND existing.actor_code IS NULL
);
