-- 115 supplemental institutions from vietnam_education_institutions_supplement_2026.json.
-- Schema taxonomy mapping: cao_dang -> COLLEGE; hoc_vien -> ACADEMY; all other
-- post-secondary units (schools, branches, faculties and institutes) -> UNIVERSITY.
INSERT INTO schools (name, abbreviation, type, ownership) VALUES
    ('Trường Đại học Việt Nhật - ĐHQG Hà Nội', 'VJU', 'UNIVERSITY', 'PUBLIC'),
    ('Học viện Âm nhạc Quốc gia Việt Nam', 'VNAM', 'ACADEMY', 'PUBLIC'),
    ('Học viện Kỹ thuật Mật mã', 'KMA', 'ACADEMY', 'PUBLIC'),
    ('Học viện Y Dược học cổ truyền Việt Nam', 'VUTM', 'ACADEMY', 'PUBLIC'),
    ('Trường Đại học Công đoàn', 'TUU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Công nghiệp Dệt May Hà Nội', 'HTU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Khoa học và Công nghệ Hà Nội', 'USTH', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Kiểm sát Hà Nội', 'HPU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Lâm nghiệp', 'VNUF', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Tài nguyên và Môi trường Hà Nội', 'HUNRE', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Thủ đô Hà Nội', 'HNMU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Phương Đông', 'PDU', 'UNIVERSITY', 'PRIVATE'),
    ('Học viện Cán bộ Thành phố Hồ Chí Minh', 'HCA', 'ACADEMY', 'PUBLIC'),
    ('Học viện Hàng không Việt Nam', 'VAA', 'ACADEMY', 'PUBLIC'),
    ('Nhạc viện Thành phố Hồ Chí Minh', 'HCMCONS', 'ACADEMY', 'PUBLIC'),
    ('Trường Đại học Mỹ thuật Thành phố Hồ Chí Minh', 'HCMUFA', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Ngân hàng Thành phố Hồ Chí Minh', 'HUB', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Sân khấu - Điện ảnh Thành phố Hồ Chí Minh', 'HCMCT', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Thể dục Thể thao Thành phố Hồ Chí Minh', 'USH', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Tôn Đức Thắng', 'TDTU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Quản lý và Công nghệ Thành phố Hồ Chí Minh', 'UMT', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Ngoại ngữ - Đại học Thái Nguyên', 'SFL-TNU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Quốc tế - Đại học Thái Nguyên', 'IS-TNU', 'UNIVERSITY', 'PUBLIC'),
    ('Phân hiệu Đại học Thái Nguyên tại Lào Cai', 'TNU-LC', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Intracom', 'INU', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Công nghiệp Quảng Ninh', 'QUI', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Công nghiệp Việt Trì', 'VUI', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Quản lý và Công nghệ Hải Phòng', 'HPMU', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Lương Thế Vinh', 'LTVU', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Điều dưỡng Nam Định', 'NDUN', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Hàng hải Việt Nam', 'VMU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Kỹ thuật Y tế Hải Dương', 'HMTU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Nông - Lâm Bắc Giang', 'BAFU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Sao Đỏ', 'SDU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Sư phạm Hà Nội 2', 'HPU2', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Sư phạm Kỹ thuật Hưng Yên', 'UTEHY', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Sư phạm Kỹ thuật Nam Định', 'NUTE', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Tài chính - Quản trị Kinh doanh', 'UFBA', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Thái Bình', 'TBU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Thành Đông', 'TDU', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Thể dục Thể thao Bắc Ninh', 'UPES1', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Trưng Vương', 'TVU', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Văn hóa, Thể thao và Du lịch Thanh Hóa', 'TUCST', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Việt Bắc', 'VBU', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Y khoa Tokyo Việt Nam', 'THUV', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Công nghệ Miền Đông', 'MIT', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Dầu khí Việt Nam', 'PVU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Đồng Nai', 'DNU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Kinh tế Công nghiệp Long An', 'DLA', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Kỹ thuật - Công nghệ Cần Thơ', 'CTUT', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Sư phạm Kỹ thuật Vĩnh Long', 'VLUTE', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Tân Tạo', 'TTU', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Thủ Dầu Một', 'TDMU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Tiền Giang', 'TGU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Xây dựng Miền Tây', 'MTU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Y Dược Cần Thơ', 'CTUMP', 'UNIVERSITY', 'PUBLIC'),
    ('Khoa Kỹ thuật và Công nghệ - Đại học Huế', 'HUET', 'UNIVERSITY', 'PUBLIC'),
    ('Khoa Quốc tế - Đại học Huế', 'HUIS', 'UNIVERSITY', 'PUBLIC'),
    ('Phân hiệu Đại học Huế tại Quảng Trị', 'HU-QT', 'UNIVERSITY', 'PUBLIC'),
    ('Khoa Giáo dục Thể chất - Đại học Đà Nẵng', 'DUPES', 'UNIVERSITY', 'PUBLIC'),
    ('Khoa Y Dược - Đại học Đà Nẵng', 'SMP-UD', 'UNIVERSITY', 'PUBLIC'),
    ('Phân hiệu Đại học Đà Nẵng tại Kon Tum', 'UD-CK', 'UNIVERSITY', 'PUBLIC'),
    ('Viện Nghiên cứu và Đào tạo Việt - Anh - Đại học Đà Nẵng', 'VNUK', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Y Dược Buôn Ma Thuột', 'BMU', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Công nghệ Vạn Xuân', 'VXUT', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Công nghiệp Vinh', 'IUV', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Hà Tĩnh', 'HTU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Khánh Hòa', 'UKH', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Kinh tế Nghệ An', 'NAUE', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Kỹ thuật Y - Dược Đà Nẵng', 'DUMTP', 'UNIVERSITY', 'PUBLIC'),
    ('Học viện Âm nhạc Huế', 'HAM', 'ACADEMY', 'PUBLIC'),
    ('Trường Đại học Phạm Văn Đồng', 'PDU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Phan Thiết', 'UPT', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Quảng Bình', 'QBU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Quảng Nam', 'QNU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Sư phạm Kỹ thuật Vinh', 'VUTE', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Tài chính - Kế toán', 'UFA', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Thái Bình Dương', 'TBD', 'UNIVERSITY', 'PRIVATE'),
    ('Trường Đại học Thể dục Thể thao Đà Nẵng', 'DSU', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Xây dựng Miền Trung', 'MUCE', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Y khoa Vinh', 'VMU', 'UNIVERSITY', 'PUBLIC'),
    ('Học viện Quốc phòng', NULL, 'ACADEMY', 'PUBLIC'),
    ('Học viện Lục quân', NULL, 'ACADEMY', 'PUBLIC'),
    ('Học viện Chính trị', NULL, 'ACADEMY', 'PUBLIC'),
    ('Học viện Hậu cần', 'HEH', 'ACADEMY', 'PUBLIC'),
    ('Học viện Kỹ thuật Quân sự', 'MTA', 'ACADEMY', 'PUBLIC'),
    ('Học viện Quân y', 'VMMU', 'ACADEMY', 'PUBLIC'),
    ('Trường Sĩ quan Lục quân 1', 'TQ1', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Sĩ quan Lục quân 2', 'TQ2', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Sĩ quan Chính trị', 'LCH', 'UNIVERSITY', 'PUBLIC'),
    ('Học viện Biên phòng', 'BPH', 'ACADEMY', 'PUBLIC'),
    ('Học viện Hải quân', 'HQH', 'ACADEMY', 'PUBLIC'),
    ('Học viện Phòng không - Không quân', 'PKH', 'ACADEMY', 'PUBLIC'),
    ('Học viện Khoa học Quân sự', 'NQH', 'ACADEMY', 'PUBLIC'),
    ('Trường Sĩ quan Pháo binh', 'PBH', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Sĩ quan Công binh', 'SNH', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Sĩ quan Thông tin', 'TTH', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Sĩ quan Không quân', 'KGH', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Sĩ quan Tăng - Thiết giáp', 'TGH', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Sĩ quan Đặc công', 'DCH', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Sĩ quan Phòng hóa', 'HGH', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Sĩ quan Kỹ thuật quân sự (Đại học Trần Đại Nghĩa)', 'VPH', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Văn hóa - Nghệ thuật Quân đội', 'ZNH', 'UNIVERSITY', 'PUBLIC'),
    ('Học viện An ninh nhân dân', 'ANH', 'ACADEMY', 'PUBLIC'),
    ('Học viện Cảnh sát nhân dân', 'CSH', 'ACADEMY', 'PUBLIC'),
    ('Học viện Chính trị Công an nhân dân', 'HCA', 'ACADEMY', 'PUBLIC'),
    ('Học viện Kỹ thuật và Công nghệ An ninh', NULL, 'ACADEMY', 'PUBLIC'),
    ('Học viện Quốc tế', NULL, 'ACADEMY', 'PUBLIC'),
    ('Trường Đại học An ninh nhân dân', 'ANS', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Cảnh sát nhân dân', 'CSS', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Đại học Phòng cháy chữa cháy', 'PCH', 'UNIVERSITY', 'PUBLIC'),
    ('Trường Cao đẳng An ninh nhân dân I', NULL, 'COLLEGE', 'PUBLIC'),
    ('Trường Cao đẳng Cảnh sát nhân dân I', NULL, 'COLLEGE', 'PUBLIC'),
    ('Trường Cao đẳng Cảnh sát nhân dân II', NULL, 'COLLEGE', 'PUBLIC'),
    ('Trường Đại học Fulbright Việt Nam', 'FUV', 'UNIVERSITY', 'PRIVATE');

CREATE INDEX IF NOT EXISTS idx_schools_active_updated_at ON schools (is_active, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_schools_type_active_updated_at ON schools (type, is_active, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_education_degree_levels_active_updated_at ON education_degree_levels (is_active, updated_at DESC);
