ALTER TABLE countries ADD COLUMN IF NOT EXISTS iso3_code VARCHAR(3);
ALTER TABLE countries ADD COLUMN IF NOT EXISTS official_name VARCHAR(255);
ALTER TABLE countries ADD COLUMN IF NOT EXISTS region VARCHAR(80);
ALTER TABLE countries ADD COLUMN IF NOT EXISTS subregion VARCHAR(120);
ALTER TABLE countries ADD COLUMN IF NOT EXISTS capital VARCHAR(255);
ALTER TABLE countries ADD COLUMN IF NOT EXISTS flag_url VARCHAR(500);
ALTER TABLE countries ADD COLUMN IF NOT EXISTS population BIGINT;
ALTER TABLE countries ADD COLUMN IF NOT EXISTS area DOUBLE PRECISION;
