CREATE TABLE IF NOT EXISTS controlled_copies (
    id UUID PRIMARY KEY,
    document_id UUID NOT NULL,
    revision_id UUID NOT NULL,
    controlled_copy_number VARCHAR(100) NOT NULL UNIQUE,
    copy_number INTEGER NOT NULL,
    total_copies INTEGER NOT NULL,
    document_number VARCHAR(100) NOT NULL,
    document_title VARCHAR(500),
    revision_number VARCHAR(50),
    business_unit_name VARCHAR(255),
    department_name VARCHAR(255),
    distribution_list TEXT,
    distribution_scope VARCHAR(50),
    location VARCHAR(255),
    location_code VARCHAR(120),
    request_reason TEXT,
    status VARCHAR(40) NOT NULL,
    current_stage VARCHAR(60),
    requested_by_user_id UUID,
    requested_at TIMESTAMP,
    approved_by_user_id UUID,
    approved_at TIMESTAMP,
    printed_by_user_id UUID,
    printed_at TIMESTAMP,
    distributed_by_user_id UUID,
    distributed_at TIMESTAMP,
    recipient_name VARCHAR(255),
    recipient_signature VARCHAR(255),
    recipient_date DATE,
    recalled_by_user_id UUID,
    recalled_at TIMESTAMP,
    recall_reason TEXT,
    destroyed_by_user_id UUID,
    destroyed_at TIMESTAMP,
    destroy_reason TEXT,
    witnessed_by VARCHAR(255),
    valid_until DATE,
    effective_date DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_controlled_copies_document FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_controlled_copies_revision FOREIGN KEY (revision_id) REFERENCES document_revisions(id),
    CONSTRAINT fk_controlled_copies_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES app_users(id),
    CONSTRAINT fk_controlled_copies_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES app_users(id),
    CONSTRAINT fk_controlled_copies_printed_by FOREIGN KEY (printed_by_user_id) REFERENCES app_users(id),
    CONSTRAINT fk_controlled_copies_distributed_by FOREIGN KEY (distributed_by_user_id) REFERENCES app_users(id),
    CONSTRAINT fk_controlled_copies_recalled_by FOREIGN KEY (recalled_by_user_id) REFERENCES app_users(id),
    CONSTRAINT fk_controlled_copies_destroyed_by FOREIGN KEY (destroyed_by_user_id) REFERENCES app_users(id)
);

CREATE INDEX IF NOT EXISTS idx_controlled_copies_status ON controlled_copies(status);
CREATE INDEX IF NOT EXISTS idx_controlled_copies_document_id ON controlled_copies(document_id);
CREATE INDEX IF NOT EXISTS idx_controlled_copies_revision_id ON controlled_copies(revision_id);
CREATE INDEX IF NOT EXISTS idx_controlled_copies_requested_at ON controlled_copies(requested_at);
