import React from "react";
import { CONTROL_STATE_CLASSES } from "@/components/ui/controlState";
import {
  SignatureFields,
  type SignatureRecord,
} from "@/features/documents/shared/components/SignatureFields";
import type { UncontrolledCopy } from "@/services/api/uncontrolledCopy";

const ReadOnlyField: React.FC<{
  label: string;
  value?: string | number | null;
}> = ({ label, value }) => (
  <div className="flex min-w-0 flex-col gap-1.5">
    <label className="text-xs font-medium text-slate-700 sm:text-sm">
      {label}
    </label>
    <input
      readOnly
      value={value ?? "-"}
      className={CONTROL_STATE_CLASSES.readonlyField}
    />
  </div>
);

/** Same readonly-input pair layout as the Revision detail's Signatures tab
 *  (@/features/documents/shared/components/SignatureFields) -- every lifecycle action always
 *  shown, not just the ones that already happened, so the user can see at a glance what's still
 *  pending versus done. */
export const UncontrolledCopyTimelineTab: React.FC<{
  copy: UncontrolledCopy;
}> = ({ copy }) => {
  const records: SignatureRecord[] = [
    {
      actionBy: "Requested By",
      actionByName: copy.requestedByName ?? "-",
      actionOn: "Requested On (Date - Time)",
      actionOnValue: copy.requestedAt ?? "",
    },
    {
      actionBy: "Approved By",
      actionByName: copy.approvedByName ?? "-",
      actionOn: "Approved On (Date - Time)",
      actionOnValue: copy.approvedAt ?? "",
    },
    {
      actionBy: "Rejected By",
      actionByName: copy.rejectedByName ?? "-",
      actionOn: "Rejected On (Date - Time)",
      actionOnValue: copy.rejectedAt ?? "",
    },
    {
      actionBy: "Generated By",
      actionByName: copy.generatedByName ?? "-",
      actionOn: "Generated On (Date - Time)",
      actionOnValue: copy.generatedAt ?? "",
    },
    {
      actionBy: "Distributed By",
      actionByName: copy.distributedByName ?? "-",
      actionOn: "Distributed On (Date - Time)",
      actionOnValue: copy.distributedAt ?? "",
    },
    {
      actionBy: "Cancelled By",
      actionByName: copy.cancelledByName ?? "-",
      actionOn: "Cancelled On (Date - Time)",
      actionOnValue: copy.cancelledAt ?? "",
    },
  ];

  const hasAnyReason = Boolean(copy.rejectionReason || copy.cancelReason);

  return (
    <div className="space-y-4 md:space-y-5">
      <SignatureFields records={records} />

      {hasAnyReason && (
        <div className="grid grid-cols-1 gap-3 pt-1 md:grid-cols-2 md:gap-4">
          {copy.rejectionReason && (
            <ReadOnlyField
              label="Rejection Reason"
              value={copy.rejectionReason}
            />
          )}
          {copy.cancelReason && (
            <ReadOnlyField label="Cancel Reason" value={copy.cancelReason} />
          )}
        </div>
      )}
    </div>
  );
};
