package com.eqms.enums;

public enum FileObjectType {
    DOCUMENT,
    REVISION,
    REVIEW_SNAPSHOT,
    PUBLISHED_PDF,
    SOURCE_DOCX,
    PUBLISHING_TEMPLATE,
    PUBLISHING_PREVIEW,
    CONTROLLED_COPY,
    CONTROLLED_COPY_EVIDENCE,
    TRAINING_MATERIAL,
    AUDIT_EXPORT,
    REPORT_EXPORT
}
