package com.eqms.enums;

public enum FileAccessAction {
    VIEW_PREVIEW,
    DOWNLOAD,
    UPLOAD,
    REPLACE,
    EDIT_ONLINE,
    VIEW_ONLINE,
    SYNC_TO_OFFICE,
    SYNC_FROM_OFFICE,
    GENERATE_PREVIEW,
    GENERATE_PUBLISHED_PDF,
    VIEW_EVIDENCE,
    DOWNLOAD_EVIDENCE,
    UPLOAD_EVIDENCE,
    GENERATE_PRESIGNED_URL,
    GENERATE_SHAREPOINT_LINK
}
