package com.eqms.enums;

public enum RevisionWorkflowAction {
    UPDATE_DRAFT_METADATA,
    UPLOAD_SOURCE,
    COMPLETE_AUTHORING,
    OPEN_PUBLISHING_WORKSPACE,
    GENERATE_REVIEW_SNAPSHOT,
    SUBMIT_FOR_REVIEW,
    COMPLETE_REVIEW,
    REJECT_REVIEW,
    COMPLETE_APPROVAL,
    REJECT_APPROVAL,
    COMPLETE_TRAINING,
    PUBLISH,
    CANCEL,
    OBSOLETE,
    UPGRADE_REVISION,
    REGENERATE_SNAPSHOT
}
