/** Shared table presentation variants. Values preserve the existing layout during migration. */
export const TABLE_STYLES = {
  headerCell1: "bg-slate-50 py-3 px-4 text-left text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap",
  table1: "border-b border-slate-200 px-2.5 py-2 text-2xs font-semibold text-slate-600 md:text-xs",
  table2: "hidden border-b border-slate-200 px-2.5 py-2 text-2xs font-semibold text-slate-600 sm:table-cell md:text-xs",
  table3: "hidden border-b border-slate-200 px-2.5 py-2 text-right text-2xs font-semibold text-slate-600 md:table-cell md:text-xs",
  table4: "hidden px-2.5 py-2 text-right text-xs tabular-nums text-slate-600 md:table-cell md:text-sm",
  emptyCell1: "p-0 border-b border-slate-200 sticky right-0 z-10 bg-slate-50/50 before:absolute before:inset-y-0 before:left-0 before:w-px before:bg-slate-200 shadow-[-6px_0_10px_-4px_rgba(0,0,0,0.05)]",
  interactiveRow1: "px-2 md:px-4 py-2 md:py-3 text-2xs md:text-xs font-semibold border-b border-r border-slate-200 cursor-pointer hover:bg-white transition-colors whitespace-nowrap",
  headerCell2: "px-2 py-2.5 sm:px-4 sm:py-3.5 text-center text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider whitespace-nowrap w-10 sm:w-16",
  headerCell3: "px-2 py-2.5 sm:px-4 sm:py-3.5 text-left text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider whitespace-nowrap",
  headerCell4: "px-3 py-2 text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider",
  headerCell5: "px-4 py-2 text-left font-bold text-slate-500 uppercase tracking-wider text-2xs md:text-xs whitespace-nowrap",
  headerCell6: "px-4 py-2.5 text-left font-bold text-slate-500 uppercase tracking-wider text-2xs md:text-xs whitespace-nowrap",
  headerCell7: "px-4 py-2.5 text-left text-2xs font-bold uppercase tracking-wider text-slate-500 md:text-xs",
  headerCell8: "py-1.5 px-2 sm:py-2.5 sm:px-4 text-center text-2xs md:text-xs font-bold uppercase tracking-wider whitespace-nowrap w-10 sm:w-12",
  headerCell9: "py-1.5 px-2 sm:py-2.5 sm:px-4 text-left text-2xs md:text-xs font-bold uppercase tracking-wider whitespace-nowrap",
  cell1: "py-1.5 px-2 sm:py-2.5 sm:px-4 text-xs sm:text-sm text-center text-slate-500 font-medium",
  cell2: "py-1.5 px-2 sm:py-2.5 sm:px-4 text-xs sm:text-sm text-slate-700 whitespace-nowrap",
  cell3: "py-1.5 px-2 sm:py-2.5 sm:px-4 text-xs sm:text-sm text-slate-700 whitespace-nowrap font-medium",
  table5: "py-1.5 px-2.5 font-medium text-emerald-600 whitespace-nowrap cursor-pointer hover:underline",
  table6: "py-1.5 px-2.5 text-center font-semibold text-slate-600 whitespace-nowrap",
  table7: "py-1.5 px-2.5 text-center text-2xs md:text-xs font-semibold text-slate-600 whitespace-nowrap w-10",
  table8: "py-1.5 px-2.5 text-center text-2xs md:text-xs font-semibold text-slate-600 whitespace-nowrap w-14 border-l border-slate-200 bg-slate-100",
  table9: "py-1.5 px-2.5 text-left text-2xs md:text-xs font-semibold text-slate-600 whitespace-nowrap",
  table10: "py-1.5 px-2.5 text-slate-700 whitespace-normal min-w-[220px] max-w-[360px]",
  cell4: "py-2 px-2 sm:py-3.5 sm:px-4 text-xs sm:text-sm text-center text-slate-500 font-medium whitespace-nowrap",
  cell5: "py-2 px-2 sm:py-3.5 sm:px-4 text-xs sm:text-sm text-slate-500 whitespace-nowrap text-center font-medium",
  cell6: "py-2 px-2 sm:py-3.5 sm:px-4 text-xs sm:text-sm text-slate-600 whitespace-nowrap",
  cell7: "py-2 px-2 sm:py-3.5 sm:px-4 text-xs sm:text-sm text-slate-600 whitespace-nowrap hidden lg:table-cell",
  cell8: "py-2 px-2 sm:py-3.5 sm:px-4 text-xs sm:text-sm text-slate-600 whitespace-nowrap hidden md:table-cell",
  cell9: "py-2 px-2 sm:py-3.5 sm:px-4 text-xs sm:text-sm text-slate-900 whitespace-nowrap",
  cell10: "py-2 px-2 sm:py-3.5 sm:px-4 text-xs sm:text-sm whitespace-nowrap font-medium text-emerald-600",
  cell11: "py-2 px-2 sm:py-3.5 sm:px-4 text-xs sm:text-sm whitespace-nowrap font-medium text-slate-900",
  cell12: "py-2 px-2 sm:py-3.5 sm:px-4 text-xs sm:text-sm whitespace-nowrap text-center text-slate-500 font-medium",
  cell13: "py-2 px-2 sm:py-3.5 sm:px-4 text-xs sm:text-sm whitespace-nowrap text-slate-600",
  cell14: "py-2 px-2 sm:py-3.5 sm:px-4 text-xs sm:text-sm whitespace-nowrap text-slate-600 hidden lg:table-cell",
  cell15: "py-2 px-2 sm:py-3.5 sm:px-4 text-xs sm:text-sm whitespace-nowrap text-slate-600 hidden md:table-cell",
  cell16: "py-2 px-2 sm:py-3.5 sm:px-4 text-xs sm:text-sm whitespace-nowrap text-slate-600 hidden xl:table-cell",
  cell17: "py-2 px-3 text-left text-2xs md:text-xs font-semibold text-slate-600 whitespace-nowrap",
  cell18: "py-2.5 px-2 md:py-3 md:px-4 text-xs md:text-sm text-slate-500 whitespace-nowrap",
  cell19: "py-2.5 px-2 md:py-3 md:px-4 text-xs md:text-sm text-slate-600 whitespace-nowrap hidden lg:table-cell",
  cell20: "py-2.5 px-2 md:py-3 md:px-4 text-xs md:text-sm text-slate-600 whitespace-nowrap hidden md:table-cell",
  cell21: "py-2.5 px-2 md:py-3 md:px-4 text-xs md:text-sm whitespace-nowrap text-slate-700",
  cell22: "py-2.5 px-2 md:py-3.5 md:px-4 text-xs md:text-sm border-b border-slate-200",
  headerCell10: "py-2.5 px-2 sm:py-3.5 sm:px-4 text-center text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider whitespace-nowrap w-10 sm:w-16",
  headerCell11: "py-2.5 px-2 sm:py-3.5 sm:px-4 text-center text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider whitespace-nowrap w-16 sm:w-24",
  headerCell12: "py-2.5 px-2 sm:py-3.5 sm:px-4 text-left text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider whitespace-nowrap",
  headerCell13: "py-2.5 px-2 sm:py-3.5 sm:px-4 text-left text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider whitespace-nowrap hidden lg:table-cell",
  headerCell14: "py-2.5 px-2 sm:py-3.5 sm:px-4 text-left text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider whitespace-nowrap hidden md:table-cell",
  headerCell15: "py-2.5 px-2 sm:py-3.5 sm:px-4 text-left text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider whitespace-nowrap hidden xl:table-cell",
  headerCell16: "py-2.5 px-2 sm:py-3.5 sm:px-4 text-left text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider whitespace-nowrap w-10 sm:w-16",
  cell23: "py-3 px-4 align-middle text-xs sm:text-sm text-slate-500 whitespace-nowrap",
  headerCell17: "py-3 px-4 text-center text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider whitespace-nowrap",
  headerCell18: "py-3 px-4 text-center text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider whitespace-nowrap w-10 sm:w-16",
  headerCell19: "py-3 px-4 text-left text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap",
  headerCell20: "py-3 px-4 text-left text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider whitespace-nowrap",
  cell24: "py-3 px-4 text-left text-xs sm:text-sm whitespace-nowrap text-slate-600 align-middle",
  cell25: "py-3 px-4 text-left text-xs sm:text-sm whitespace-nowrap text-slate-700 align-middle",
  cell26: "py-3 px-4 text-xs sm:text-sm text-slate-500 font-medium whitespace-nowrap text-center",
  cell27: "py-3 px-4 text-xs sm:text-sm whitespace-nowrap font-medium text-emerald-600 cursor-pointer hover:underline",
  cell28: "py-3 px-4 text-xs sm:text-sm whitespace-nowrap font-medium text-slate-900",
  cell29: "py-3 px-4 text-xs sm:text-sm whitespace-nowrap text-slate-500 text-center",
  cell30: "py-3 px-4 text-xs sm:text-sm whitespace-nowrap text-slate-700 text-center",
  cell31: "py-3 px-4 text-xs sm:text-sm whitespace-nowrap text-slate-700 text-left align-middle",
  emptyCell2: "sticky right-0 bg-white py-3 px-4 text-center z-10 whitespace-nowrap before:content-[''] before:absolute before:left-0 before:top-0 before:bottom-0 before:w-[1px] before:bg-slate-200 shadow-[-4px_0_12px_-4px_rgba(0,0,0,0.05)] group-hover:bg-slate-50",
  emptyCell3: "sticky right-0 bg-white py-3 px-4 text-xs sm:text-sm text-center z-30 whitespace-nowrap before:content-[''] before:absolute before:left-0 before:top-0 before:bottom-0 before:w-[1px] before:bg-slate-200 shadow-[-4px_0_12px_-4px_rgba(0,0,0,0.05)] group-hover:bg-slate-50",
  headerCell21: "sticky right-0 top-0 z-30 w-20 whitespace-nowrap border-b-2 border-slate-200 bg-slate-50 px-4 py-3 text-center text-2xs font-bold uppercase tracking-wider text-slate-500 shadow-[-6px_0_10px_-4px_rgba(0,0,0,0.05)] before:absolute before:inset-y-0 before:left-0 before:w-px before:bg-slate-200 md:text-xs",
  cell32: "sticky right-0 z-10 bg-white border-b border-slate-200 py-1.5 px-2 md:py-2 md:px-4 text-center whitespace-nowrap before:absolute before:inset-y-0 before:left-0 before:w-px before:bg-slate-200 shadow-[-6px_0_10_rgba(0,0,0,0.05)] group-hover:bg-slate-50 transition-colors",
  cell33: "sticky right-0 z-10 bg-white border-b border-slate-200 py-3 px-4 text-center whitespace-nowrap before:absolute before:inset-y-0 before:left-0 before:w-px before:bg-slate-200 shadow-[-6px_0_10px_-4px_rgba(0,0,0,0.05)] group-hover:bg-slate-50 transition-colors",
  cell34: "sticky right-0 z-10 bg-white py-3 px-4 text-center whitespace-nowrap before:absolute before:inset-y-0 before:left-0 before:w-px before:bg-slate-200 shadow-[-6px_0_10px_-4px_rgba(0,0,0,0.05)] group-hover:bg-slate-50 transition-colors",
  cell35: "sticky right-0 z-30 whitespace-nowrap bg-white px-4 py-3 text-center shadow-[-6px_0_10px_-4px_rgba(0,0,0,0.05)] before:absolute before:inset-y-0 before:left-0 before:w-px before:bg-slate-200 group-hover:bg-slate-50",
  headerCell22: "sticky top-0 right-0 z-30 bg-slate-50 py-1.5 px-2 md:py-2.5 md:px-4 text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider text-center whitespace-nowrap border-b-2 border-slate-200 before:absolute before:inset-y-0 before:left-0 before:w-px before:bg-slate-200 shadow-[-6px_0_10px_-4px_rgba(0,0,0,0.05)]",
  headerCell23: "sticky top-0 right-0 z-30 bg-slate-50 py-2.5 px-2 md:py-3.5 md:px-4 text-center text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap before:absolute before:inset-y-0 before:left-0 before:w-px before:bg-slate-200 shadow-[-6px_0_10px_-4px_rgba(0,0,0,0.05)]",
  headerCell24: "sticky top-0 right-0 z-30 bg-slate-50 py-3 px-4 text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap text-center before:absolute before:inset-y-0 before:left-0 before:w-px before:bg-slate-200 shadow-[-6px_0_10px_-4px_rgba(0,0,0,0.05)]",
  headerCell25: "sticky top-0 right-0 z-30 bg-slate-50 py-3 px-4 text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider text-center whitespace-nowrap border-b-2 border-slate-200 before:absolute before:inset-y-0 before:left-0 before:w-px before:bg-slate-200 shadow-[-6px_0_10px_-4px_rgba(0,0,0,0.05)]",
  headerCell26: "sticky top-0 right-0 z-30 bg-slate-50 py-3 px-4 text-center text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap before:absolute before:inset-y-0 before:left-0 before:w-px before:bg-slate-200 shadow-[-6px_0_10px_-4px_rgba(0,0,0,0.05)]",
  headerCell27: "sticky top-0 z-10 bg-slate-50 py-3 px-4 text-left text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap",
  headerCell28: "sticky top-0 z-20 bg-slate-50 py-2.5 px-2 md:py-3.5 md:px-4 text-center text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap w-16",
  emptyCell4: "sticky top-0 z-20 bg-slate-50 py-3 px-2 border-b-2 border-slate-200 w-8",
  headerCell29: "sticky top-0 z-20 bg-slate-50 py-3 px-4 text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap text-center",
  headerCell30: "sticky top-0 z-20 bg-slate-50 py-3 px-4 text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap transition-colors cursor-pointer hover:bg-slate-100 hover:text-slate-700 group",
  headerCell31: "sticky top-0 z-20 bg-slate-50 py-3 px-4 text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap transition-colors w-44",
  headerCell32: "sticky top-0 z-20 bg-slate-50 py-3 px-4 text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap w-9",
  headerCell33: "sticky top-0 z-20 bg-slate-50 py-3 px-4 text-center text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap w-12",
  headerCell34: "sticky top-0 z-20 bg-slate-50 py-3 px-4 text-center text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap w-14",
  headerCell35: "sticky top-0 z-20 bg-slate-50 py-3 px-4 text-center text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap w-16",
  headerCell36: "sticky top-0 z-20 bg-slate-50 py-3 px-4 text-center text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap w-9",
  headerCell37: "sticky top-0 z-20 bg-slate-50 py-3 px-4 text-left text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap",
  headerCell38: "sticky top-0 z-20 bg-slate-50 py-3 px-4 text-left text-2xs md:text-xs font-bold text-slate-500 uppercase tracking-wider border-b-2 border-slate-200 whitespace-nowrap cursor-pointer hover:bg-slate-100 hover:text-slate-700 transition-colors group",
  headerCell39: "sticky top-0 z-20 cursor-pointer whitespace-nowrap border-b-2 border-slate-200 bg-slate-50 px-4 py-3 text-left text-2xs font-bold uppercase tracking-wider text-slate-500 transition-colors hover:bg-slate-100 hover:text-slate-700 group md:text-xs",
  headerCell40: "sticky top-0 z-20 w-16 whitespace-nowrap border-b-2 border-slate-200 bg-slate-50 px-4 py-3 text-center text-2xs md:text-xs font-bold uppercase tracking-wider text-slate-500",
  headerCell41: "sticky top-0 z-20 whitespace-nowrap border-b-2 border-slate-200 bg-slate-50 px-4 py-3 text-2xs font-bold uppercase tracking-wider text-slate-500 md:text-xs",
  headerCell42: "sticky top-0 z-20 whitespace-nowrap border-b-2 border-slate-200 bg-slate-50 px-4 py-3 text-left text-2xs font-bold uppercase tracking-wider text-slate-500 md:text-xs",
  headerCell43: "text-left px-3 py-2 text-2xs md:text-xs font-semibold text-slate-500 uppercase tracking-wider",
  headerCell44: "w-1/3 px-4 py-2.5 text-left text-2xs font-bold uppercase tracking-wider text-slate-500 md:text-xs",
  headerCell45: "w-1/4 px-4 py-2.5 text-left text-2xs font-bold uppercase tracking-wider text-slate-500 md:text-xs",
  table11: "w-full min-w-[800px] md:min-w-[950px] lg:min-w-[1100px] xl:min-w-[1300px]",
  cell36: "whitespace-nowrap px-4 py-3 text-center text-xs text-slate-500 sm:text-sm",
} as const;

