import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { PageHeader } from "@/components/ui/page/PageHeader";
import { FormSection } from "@/components/ui/form/FormSection";
import { TabNav } from "@/components/ui/tabs/TabNav";
import { Button } from "@/components/ui/button/Button";
import { reportsApi, type ReportDefinition } from "@/services/api/reports";
import { dictionaryApi } from "@/services/api/dictionary";
import type { RetentionPolicyItem } from "@/features/settings/dictionaries/types";
import { Settings2 } from "lucide-react";
import { TableMarkup } from "@/components/ui/table/TablePrimitives";

const tabs = [{ id: "general", label: "General" }, { id: "fields", label: "Fields & Defaults" }, { id: "scope", label: "Access & Scope" }, { id: "delivery", label: "Delivery & Retention" }, { id: "history", label: "History" }] as const;
export function ReportDefinitionEditView() {
  const { code = "" } = useParams(); const navigate = useNavigate(); const [active, setActive] = useState("general"); const [definition, setDefinition] = useState<ReportDefinition | null>(null); const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false); const [history, setHistory] = useState<Array<{ version: number; reason: string; changedByUserId: string; createdAt: string }>>([]); const [retentionPolicies, setRetentionPolicies] = useState<RetentionPolicyItem[]>([]);
  useEffect(() => { reportsApi.getDefinition(code).then(setDefinition); }, [code]);
  useEffect(() => { dictionaryApi.getRetentionPolicies().then(items => setRetentionPolicies(items.filter(item => item.isActive))); }, []);
  useEffect(() => { if (active === "history") reportsApi.definitionHistory(code).then(setHistory); }, [active, code]);
  const fields = useMemo(() => definition?.fields ?? [], [definition]);
  if (!definition) return <p className="p-5 text-sm text-slate-500">Loading report definition…</p>;
  const save = async () => { if (!reason.trim()) return; setSaving(true); try { await reportsApi.updateDefinition(code, { displayName: definition.displayName, description: definition.description, category: definition.category, classification: definition.classification, active: definition.active, retentionPolicyId: definition.retentionPolicyId ?? null, reason }); setReason(""); setDefinition(await reportsApi.getDefinition(code)); } finally { setSaving(false); } };
  const saveFields = async () => { if (!reason.trim()) return; setSaving(true); try { await reportsApi.updateDefinitionFields(code, { reason, fields }); setReason(""); setDefinition(await reportsApi.getDefinition(code)); } finally { setSaving(false); } };
  const updateField = (fieldCode: string, change: Partial<(typeof fields)[number]>) => setDefinition(current => current ? { ...current, fields: current.fields.map(field => field.code === fieldCode ? { ...field, ...change, defaultSelected: change.required ? true : (change.defaultSelected ?? field.defaultSelected) } : field) } : current);
  return <div className="flex min-h-0 flex-1 flex-col gap-5"><PageHeader title={`Edit ${definition.displayName}`} breadcrumbItems={[{ label: "Application Settings", onClick: () => navigate("/settings/dictionaries") }, { label: "Report Configuration", onClick: () => navigate("/settings/report-configuration") }, { label: "Edit Definition" }]} actions={<Button variant="outline" size="sm" onClick={() => navigate("/settings/report-configuration")}>Back</Button>} />
    <FormSection title="Report Definition" description="Controlled configuration. Dataset logic and authorization remain server-owned." icon={<Settings2 className="h-4 w-4" />}><TabNav tabs={tabs} activeTab={active} onChange={setActive} variant="underline" ariaLabel="Report definition sections" />
      {active === "general" && <div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-slate-700">Display name<input className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={definition.displayName} onChange={e => setDefinition({ ...definition, displayName: e.target.value })} /></label><label className="text-sm font-medium text-slate-700">Category<input className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" value={definition.category} onChange={e => setDefinition({ ...definition, category: e.target.value })} /></label><label className="md:col-span-2 text-sm font-medium text-slate-700">Description<textarea className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" rows={3} value={definition.description ?? ""} onChange={e => setDefinition({ ...definition, description: e.target.value })} /></label><label className="md:col-span-2 text-sm font-medium text-slate-700">Change reason<textarea className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" rows={2} value={reason} onChange={e => setReason(e.target.value)} placeholder="Required for controlled configuration changes" /></label><div className="md:col-span-2 flex justify-end"><Button size="sm" disabled={!reason.trim() || saving} onClick={save}>{saving ? "Saving…" : "Save Configuration"}</Button></div></div>}
      {active === "fields" && <div className="mt-5"><p className="mb-4 text-sm text-slate-600">Required fields are always selected. Technical fields cannot be added from this screen.</p><div className="overflow-x-auto"><TableMarkup.Root className="w-full min-w-[720px] text-sm"><TableMarkup.Head className="bg-slate-50 text-left text-xs font-semibold uppercase text-slate-500"><TableMarkup.Row><TableMarkup.HeaderCell className="px-3 py-2">Field</TableMarkup.HeaderCell><TableMarkup.HeaderCell className="px-3 py-2">Type</TableMarkup.HeaderCell><TableMarkup.HeaderCell className="px-3 py-2">Allowed</TableMarkup.HeaderCell><TableMarkup.HeaderCell className="px-3 py-2">Default</TableMarkup.HeaderCell><TableMarkup.HeaderCell className="px-3 py-2">Required</TableMarkup.HeaderCell><TableMarkup.HeaderCell className="px-3 py-2">Order</TableMarkup.HeaderCell></TableMarkup.Row></TableMarkup.Head><TableMarkup.Body>{fields.map(f => <TableMarkup.Row key={f.code} className="border-t border-slate-100"><TableMarkup.Cell className="px-3 py-3"><p className="font-medium">{f.name}</p><p className="font-mono text-xs text-slate-500">{f.code}</p></TableMarkup.Cell><TableMarkup.Cell className="px-3 py-3">{f.type}</TableMarkup.Cell><TableMarkup.Cell className="px-3 py-3"><input type="checkbox" checked={f.allowed} onChange={e => updateField(f.code, { allowed: e.target.checked })} /></TableMarkup.Cell><TableMarkup.Cell className="px-3 py-3"><input type="checkbox" checked={f.defaultSelected} disabled={f.required || !f.allowed} onChange={e => updateField(f.code, { defaultSelected: e.target.checked })} /></TableMarkup.Cell><TableMarkup.Cell className="px-3 py-3"><input type="checkbox" checked={f.required} disabled={!f.allowed} onChange={e => updateField(f.code, { required: e.target.checked })} /></TableMarkup.Cell><TableMarkup.Cell className="px-3 py-3"><input type="number" className="w-20 rounded border border-slate-200 px-2 py-1" value={f.order} onChange={e => updateField(f.code, { order: Number(e.target.value) })} /></TableMarkup.Cell></TableMarkup.Row>)}</TableMarkup.Body></TableMarkup.Root></div><label className="mt-4 block text-sm font-medium text-slate-700">Change reason<textarea className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" rows={2} value={reason} onChange={e => setReason(e.target.value)} placeholder="Required for controlled configuration changes" /></label><div className="mt-4 flex justify-end"><Button size="sm" disabled={!reason.trim() || saving} onClick={saveFields}>{saving ? "Saving…" : "Save Fields & Defaults"}</Button></div></div>}
      {active === "scope" && <p className="mt-5 text-sm text-slate-600">Access is evaluated by the report permission and the source resource authorization engine at runtime. This configuration never grants visibility beyond source scope.</p>}
      {active === "delivery" && <div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-slate-700">Retention policy<select className="mt-1 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm" value={definition.retentionPolicyId ?? ""} onChange={e => { const policy = retentionPolicies.find(item => item.id === e.target.value); setDefinition({ ...definition, retentionPolicyId: e.target.value || null, retentionPolicyName: policy?.name ?? null, retentionDays: policy?.retentionDays ?? null }); }}><option value="">Permanent retention</option>{retentionPolicies.map(policy => <option key={policy.id} value={policy.id}>{policy.name}{policy.retentionDays ? ` (${policy.retentionDays} days)` : " (permanent)"}</option>)}</select><p className="mt-1 text-xs font-normal text-slate-500">The selected policy is snapshotted when an artifact is generated. A legal hold always prevents purge.</p></label><div className="rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600"><p className="font-medium text-slate-800">Authenticated delivery</p><p className="mt-1">Artifacts are immutable, checksum-verified and re-authorized for each download. Email sends only an authenticated link; attachments are not supported.</p></div><label className="md:col-span-2 text-sm font-medium text-slate-700">Change reason<textarea className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" rows={2} value={reason} onChange={e => setReason(e.target.value)} placeholder="Required for controlled configuration changes" /></label><div className="md:col-span-2 flex justify-end"><Button size="sm" disabled={!reason.trim() || saving} onClick={save}>{saving ? "Saving…" : "Save Delivery & Retention"}</Button></div></div>}
      {active === "history" && <div className="mt-5 overflow-x-auto"><TableMarkup.Root className="w-full min-w-[620px] text-sm"><TableMarkup.Head className="bg-slate-50 text-left text-xs font-semibold uppercase text-slate-500"><TableMarkup.Row><TableMarkup.HeaderCell className="px-3 py-2">Version</TableMarkup.HeaderCell><TableMarkup.HeaderCell className="px-3 py-2">Reason</TableMarkup.HeaderCell><TableMarkup.HeaderCell className="px-3 py-2">Changed by</TableMarkup.HeaderCell><TableMarkup.HeaderCell className="px-3 py-2">Timestamp</TableMarkup.HeaderCell></TableMarkup.Row></TableMarkup.Head><TableMarkup.Body>{history.map(item => <TableMarkup.Row key={item.version} className="border-t border-slate-100"><TableMarkup.Cell className="px-3 py-3">v{item.version}</TableMarkup.Cell><TableMarkup.Cell className="px-3 py-3">{item.reason}</TableMarkup.Cell><TableMarkup.Cell className="px-3 py-3 font-mono text-xs">{item.changedByUserId}</TableMarkup.Cell><TableMarkup.Cell className="px-3 py-3">{item.createdAt}</TableMarkup.Cell></TableMarkup.Row>)}</TableMarkup.Body></TableMarkup.Root></div>}
    </FormSection></div>;
}
