package com.eqms.dto.user;

/**
 * Read-only storage paths generated by the same backend builders used for persisted files.
 * Placeholder segments make the configured structure understandable without exposing a real object key.
 */
public record StoragePathPreviewResponse(
        String officeOnlineWorkspace,
        String documents,
        String controlledCopies,
        String templates,
        String training,
        String auditEvidence,
        String temporaryFiles
) {
}
