export interface PermissionDescriptor {
  code: string;
  label: string;
  description: string;
  module: string;
  group: string;
  legacyCodes?: string[];
}

const LEGACY_PERMISSION_CATALOG: PermissionDescriptor[] = [
  // ─── Notifications ──────────────────────────────────────────────────────────
  {
    code: "notifications.module.view",
    label: "View Notifications",
    description: "Access in-app notifications and alerts.",
    module: "notifications",
    group: "notifications_access",
  },
  {
    code: "notifications.recipient.qa_manager",
    label: "Receive QA Manager Notifications",
    description: "Receive notification-policy events addressed to the configured QA Manager audience.",
    module: "notifications",
    group: "notification_recipients",
  },

  // ─── Dashboard ──────────────────────────────────────────────────────────────
  {
    code: "dashboard.module.view",
    label: "View Dashboard",
    description: "Access the system dashboard and summary widgets.",
    module: "dashboard",
    group: "dashboard_access",
  },
  {
    code: "dashboard.admin.view",
    label: "View Administrative Dashboard",
    description: "View administrative dashboard statistics and security-oriented overview widgets.",
    module: "dashboard",
    group: "dashboard_admin",
  },

  // ─── My Tasks ───────────────────────────────────────────────────────────────
  // ─── Document Control ───────────────────────────────────────────────────────
  {
    code: "documents.module.view",
    label: "View Document Control",
    description: "Access the Document Control module, including documents and revisions.",
    module: "documents",
    group: "document_control_access",
    legacyCodes: ["VIEW_DOCUMENTS"],
  },
  {
    code: "documents.document.view",
    label: "View Documents",
    description: "View documents and revisions permitted by the user's access scope.",
    module: "documents",
    group: "document_control_access",
  },
  {
    code: "documents.document.view_all",
    label: "View All Document Records",
    description: "View every document and revision, including records outside the user's business-unit scope. This permission is read-only.",
    module: "documents",
    group: "document_control_access",
  },
  {
    code: "documents.workspace.manage",
    label: "Manage Document Control Workspace",
    description: "Perform Document Control operational actions that are separately allowed by lifecycle and workflow policy. This does not grant authoring access to another user's Draft.",
    module: "documents",
    group: "document_control_access",
  },
  {
    code: "documents.document.configure_initial_workflow",
    label: "Configure Initial Document Workflow",
    description: "Select the initial reviewers, approvers, and document relationships while creating a new Document Master.",
    module: "documents",
    group: "document_authoring",
  },
  {
    code: "documents.revision.configure_next_reviewers",
    label: "Configure Next Revision Reviewers",
    description: "Change the reviewer routing inherited by the next revision of an Active document.",
    module: "documents",
    group: "document_authoring",
  },
  {
    code: "documents.revision.configure_next_approvers",
    label: "Configure Next Revision Approvers",
    description: "Change the approver routing inherited by the next revision of an Active document.",
    module: "documents",
    group: "document_authoring",
  },
  {
    code: "documents.revision.configure_next_related_documents",
    label: "Configure Next Revision Related Documents",
    description: "Change related documents inherited by the next revision of an Active document.",
    module: "documents",
    group: "document_authoring",
  },
  {
    code: "documents.revision.configure_next_correlated_documents",
    label: "Configure Next Revision Correlated Documents",
    description: "Change correlated documents inherited by the next revision of an Active document.",
    module: "documents",
    group: "document_authoring",
  },
  {
    code: "documents.document.create",
    label: "Create Document Shell",
    description: "Create a new document shell with metadata and workflow configuration.",
    module: "documents",
    group: "document_authoring",
    legacyCodes: ["CREATE_DOCUMENT_SHELL", "CREATE_DOCUMENTS"],
  },
  {
    code: "documents.document.edit_metadata",
    label: "Edit Document Metadata",
    description: "Update document metadata, ownership, and routing settings.",
    module: "documents",
    group: "document_authoring",
    legacyCodes: ["EDIT_DOCUMENT_METADATA", "EDIT_DOCUMENTS"],
  },
  {
    code: "documents.document.view_audit",
    label: "View Document Audit Trail",
    description: "View audit trail history for document and revision records.",
    module: "documents",
    group: "document_compliance",
    legacyCodes: ["VIEW_DOCUMENT_AUDIT_TRAIL", "VIEW_AUDIT_TRAIL"],
  },
  {
    code: "documents.document.obsolete",
    label: "Obsolete Document",
    description: "Obsolete an active document and its current lifecycle.",
    module: "documents",
    group: "document_lifecycle",
    legacyCodes: ["OBSOLETE_DOCUMENT"],
  },
  {
    code: "documents.document.cancel",
    label: "Cancel Document",
    description: "Cancel a document master lifecycle when its status allows it.",
    module: "documents",
    group: "document_lifecycle",
  },
  {
    code: "documents.document.preview_published",
    label: "Preview Published Document",
    description: "Open the controlled preview of a published document.",
    module: "documents",
    group: "document_access",
  },
  {
    code: "documents.document.download_published",
    label: "Download Published Document",
    description: "Download a published document when download policy permits it.",
    module: "documents",
    group: "document_access",
  },
  {
    code: "documents.revision.upload_source",
    label: "Upload Revision Source",
    description: "Upload or replace the controlled source file for an authorised Draft revision.",
    module: "documents",
    group: "revision_authoring",
    legacyCodes: ["UPLOAD_REVISION_FILE"],
  },
  {
    code: "documents.revision.submit_review",
    label: "Submit Revision for Review",
    description: "Submit a draft revision into the controlled workflow.",
    module: "documents",
    group: "revision_workflow",
    legacyCodes: ["SUBMIT_REVISION"],
  },
  {
    code: "documents.revision.review",
    label: "Review Revision",
    description: "Perform the assigned review step in a revision workflow.",
    module: "documents",
    group: "revision_workflow",
    legacyCodes: ["COMPLETE_REVIEW", "REVIEW_DOCUMENTS"],
  },
  {
    code: "documents.revision.approve",
    label: "Approve Revision",
    description: "Perform the assigned approval step in a revision workflow.",
    module: "documents",
    group: "revision_workflow",
    legacyCodes: ["APPROVE_REVISION", "APPROVE_DOCUMENTS"],
  },
  {
    code: "documents.revision.reject_review",
    label: "Reject Review",
    description: "Reject an assigned review and return the revision to authoring.",
    module: "documents",
    group: "revision_workflow",
    legacyCodes: ["REJECT_REVISION"],
  },
  {
    code: "documents.revision.reject_approval",
    label: "Reject Approval",
    description: "Reject an assigned approval and return the revision to the configured prior stage.",
    module: "documents",
    group: "revision_workflow",
  },
  {
    code: "documents.revision.complete_authoring",
    label: "Complete Authoring",
    description: "Complete authoring for a draft revision before it is submitted for review.",
    module: "documents",
    group: "revision_workflow",
  },
  {
    code: "documents.revision.open_publishing_workspace",
    label: "Open Publishing Workspace",
    description: "Open the publishing workspace for an authorised Ready for Publishing revision. Publishing remains a separate permission.",
    module: "documents",
    group: "revision_publish",
  },
  {
    code: "documents.revision.complete_training",
    label: "Complete Revision Training",
    description: "Record completion of the revision training workflow stage.",
    module: "documents",
    group: "training_publish",
  },
  {
    code: "documents.revision.cancel",
    label: "Cancel Revision",
    description: "Cancel a revision while it is in an allowed in-progress lifecycle state.",
    module: "documents",
    group: "revision_workflow",
  },
  {
    code: "documents.revision.preview",
    label: "Preview Revision",
    description: "Preview revision content when the lifecycle and access policy allow it.",
    module: "documents",
    group: "revision_access",
  },
  {
    code: "documents.revision.download_source",
    label: "Download Revision Source",
    description: "Download a revision source file when its access policy permits it.",
    module: "documents",
    group: "revision_access",
  },
  {
    code: "documents.revision.edit_online",
    label: "Edit Revision Online",
    description: "Edit an authorized draft revision in the integrated online editor.",
    module: "documents",
    group: "revision_authoring",
  },
  {
    code: "documents.revision.generate_preview",
    label: "Generate Revision Preview",
    description: "Generate the controlled preview used by the revision workflow.",
    module: "documents",
    group: "revision_authoring",
  },
  {
    code: "documents.revision.upload_office_online",
    label: "Upload Revision to Office Online",
    description: "Upload or synchronize an authorised Draft revision working copy with Office Online.",
    module: "documents",
    group: "revision_authoring",
  },
  {
    code: "documents.revision.upgrade",
    label: "Upgrade Revision",
    description: "Create or upgrade a revision from an eligible document lifecycle state.",
    module: "documents",
    group: "revision_authoring",
  },
  {
    code: "documents.revision.publish",
    label: "Publish Revision",
    description: "Publish an approved revision and make it effective.",
    module: "documents",
    group: "revision_publish",
    legacyCodes: ["PUBLISH_REVISION", "PUBLISH_DOCUMENTS"],
  },
  {
    code: "documents.training.manage",
    label: "Manage Training Plan",
    description: "Manage training plan, effective distribution, and related assignments.",
    module: "documents",
    group: "training_publish",
    legacyCodes: ["MANAGE_TRAINING_PLAN"],
  },
  {
    code: "documents.training.complete",
    label: "Complete Training",
    description: "Complete assigned training steps for a document revision.",
    module: "documents",
    group: "training_publish",
    legacyCodes: ["COMPLETE_TRAINING"],
  },
  {
    code: "documents.controlled_copy.request",
    label: "Request Controlled Copy",
    description: "Request issuance or delivery of a controlled copy.",
    module: "documents",
    group: "controlled_copies",
    legacyCodes: ["REQUEST_CONTROLLED_COPY"],
  },
  {
    code: "documents.controlled_copy.distribute",
    label: "Distribute Controlled Copy",
    description: "Distribute a controlled copy batch that is ready for distribution.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.recall",
    label: "Recall Controlled Copy",
    description: "Recall a distributed controlled copy.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.cancel_request",
    label: "Cancel Controlled Copy Request",
    description: "Cancel an open controlled copy request.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.replace_lost_damaged",
    label: "Replace Lost or Damaged Copy",
    description: "Replace a controlled copy after a lost or damaged copy event.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.report_lost_damaged",
    label: "Report Lost or Damaged Copy",
    description: "Report that an issued controlled copy has been lost or damaged.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.expire",
    label: "Expire Controlled Copy",
    description: "Expire a controlled copy according to its lifecycle policy.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.view",
    label: "View Controlled Copy Records",
    description: "View controlled-copy requests, batches, recipients, and lifecycle status.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.view_file",
    label: "View Controlled Copy",
    description: "View a controlled copy file within the authorized access scope.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.download_file",
    label: "Download Controlled Copy",
    description: "Download a controlled copy file when download policy permits it.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.view_evidence",
    label: "View Controlled Copy Evidence",
    description: "View controlled copy distribution and acknowledgement evidence.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.download_evidence",
    label: "Download Controlled Copy Evidence",
    description: "Download controlled copy evidence when policy permits it.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.upload_evidence",
    label: "Upload Controlled Copy Evidence",
    description: "Upload controlled-copy acknowledgement, return, or incident evidence.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.admin.view",
    label: "Access Document Administration",
    description: "Open Document Administration and review system workflow settings.",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.manage_workflow_roles",
    label: "Manage Document Workflow Roles",
    description: "Manage workflow-coordinator, reviewer, and approver assignments for Document Control.",
    module: "documents",
    group: "document_administration",
  },
  // ─── Training Management ─────────────────────────────────────────────────────
  {
    code: "training.module.view",
    label: "View Training",
    description: "Access the Training module and assigned training workflows.",
    module: "training",
    group: "training_access",
  },
  {
    code: "training.material.manage",
    label: "Manage Training Materials",
    description: "Create, update, review, and approve training materials and courses.",
    module: "training",
    group: "training_admin",
  },
  {
    code: "training.session.manage",
    label: "Manage Training Sessions",
    description: "Schedule and manage training sessions and attendance records.",
    module: "training",
    group: "training_admin",
  },
  {
    code: "training.assignment.manage",
    label: "Manage Training Assignments",
    description: "Assign training courses and requirements to users or groups.",
    module: "training",
    group: "training_admin",
  },

  // ─── Deviations & NCs ────────────────────────────────────────────────────────
  {
    code: "deviations.module.view",
    label: "View Deviations & NCs",
    description: "Access the Deviations & Non-Conformances module.",
    module: "deviations",
    group: "deviations_access",
  },
  {
    code: "deviations.record.create",
    label: "Report Deviation / NC",
    description: "Create and submit a new deviation or non-conformance report.",
    module: "deviations",
    group: "deviations_actions",
  },
  {
    code: "deviations.record.edit",
    label: "Edit Deviation Record",
    description: "Edit an existing deviation or non-conformance record.",
    module: "deviations",
    group: "deviations_actions",
  },
  {
    code: "deviations.record.investigate",
    label: "Investigate Deviation",
    description: "Perform root cause analysis and document investigation findings.",
    module: "deviations",
    group: "deviations_actions",
  },
  {
    code: "deviations.record.approve",
    label: "Approve Deviation",
    description: "Review and approve a deviation investigation outcome.",
    module: "deviations",
    group: "deviations_actions",
  },
  {
    code: "deviations.record.close",
    label: "Close Deviation",
    description: "Close a resolved deviation or non-conformance record.",
    module: "deviations",
    group: "deviations_actions",
  },

  // ─── CAPA Management ─────────────────────────────────────────────────────────
  {
    code: "capa.module.view",
    label: "View CAPA",
    description: "Access the CAPA Management module.",
    module: "capa",
    group: "capa_access",
  },
  {
    code: "capa.record.create",
    label: "Create CAPA",
    description: "Create a new corrective or preventive action record.",
    module: "capa",
    group: "capa_actions",
  },
  {
    code: "capa.record.edit",
    label: "Edit CAPA Record",
    description: "Edit an existing CAPA record or action plan.",
    module: "capa",
    group: "capa_actions",
  },
  {
    code: "capa.record.assign",
    label: "Assign CAPA Actions",
    description: "Assign tasks and responsible owners to CAPA action items.",
    module: "capa",
    group: "capa_actions",
  },
  {
    code: "capa.record.implement",
    label: "Implement CAPA Action",
    description: "Record implementation evidence for assigned CAPA actions.",
    module: "capa",
    group: "capa_actions",
  },
  {
    code: "capa.record.verify",
    label: "Verify CAPA Effectiveness",
    description: "Perform and record effectiveness verification for a closed CAPA.",
    module: "capa",
    group: "capa_actions",
  },
  {
    code: "capa.record.close",
    label: "Close CAPA",
    description: "Close a verified and completed CAPA record.",
    module: "capa",
    group: "capa_actions",
  },

  // ─── Change Controls ─────────────────────────────────────────────────────────
  {
    code: "change_control.module.view",
    label: "View Change Controls",
    description: "Access the Change Controls module.",
    module: "change-control",
    group: "change_control_access",
  },
  {
    code: "change_control.record.create",
    label: "Create Change Control",
    description: "Create a new change control request.",
    module: "change-control",
    group: "change_control_actions",
  },
  {
    code: "change_control.record.edit",
    label: "Edit Change Control",
    description: "Edit a change control request record.",
    module: "change-control",
    group: "change_control_actions",
  },
  {
    code: "change_control.record.review",
    label: "Review Change Control",
    description: "Perform an assigned review step for a change control request.",
    module: "change-control",
    group: "change_control_actions",
  },
  {
    code: "change_control.record.approve",
    label: "Approve Change Control",
    description: "Approve a change control request to proceed with implementation.",
    module: "change-control",
    group: "change_control_actions",
  },
  {
    code: "change_control.record.implement",
    label: "Implement Change Control",
    description: "Record implementation details and evidence for an approved change.",
    module: "change-control",
    group: "change_control_actions",
  },
  {
    code: "change_control.record.close",
    label: "Close Change Control",
    description: "Close a fully implemented and verified change control.",
    module: "change-control",
    group: "change_control_actions",
  },

  // ─── Complaints Management ───────────────────────────────────────────────────
  {
    code: "complaints.module.view",
    label: "View Complaints",
    description: "Access the Complaints Management module.",
    module: "complaints",
    group: "complaints_access",
  },
  {
    code: "complaints.record.create",
    label: "Create Complaint",
    description: "Create and submit a new customer or regulatory complaint record.",
    module: "complaints",
    group: "complaints_actions",
  },
  {
    code: "complaints.record.edit",
    label: "Edit Complaint Record",
    description: "Edit an existing complaint record.",
    module: "complaints",
    group: "complaints_actions",
  },
  {
    code: "complaints.record.investigate",
    label: "Investigate Complaint",
    description: "Perform investigation and document findings for a complaint.",
    module: "complaints",
    group: "complaints_actions",
  },
  {
    code: "complaints.record.close",
    label: "Close Complaint",
    description: "Close a resolved complaint record.",
    module: "complaints",
    group: "complaints_actions",
  },

  // ─── Risk Management ─────────────────────────────────────────────────────────
  {
    code: "risk_management.module.view",
    label: "View Risk Management",
    description: "Access the Risk Management module.",
    module: "risk-management",
    group: "risk_access",
  },
  {
    code: "risk_management.record.create",
    label: "Create Risk Assessment",
    description: "Create a new risk assessment record.",
    module: "risk-management",
    group: "risk_actions",
  },
  {
    code: "risk_management.record.edit",
    label: "Edit Risk Record",
    description: "Edit an existing risk record or assessment.",
    module: "risk-management",
    group: "risk_actions",
  },
  {
    code: "risk_management.record.review",
    label: "Review Risk Assessment",
    description: "Review and score a risk assessment.",
    module: "risk-management",
    group: "risk_actions",
  },
  {
    code: "risk_management.record.approve",
    label: "Approve Risk",
    description: "Approve and accept a reviewed risk assessment.",
    module: "risk-management",
    group: "risk_actions",
  },

  // ─── Equipment Management ────────────────────────────────────────────────────
  {
    code: "equipment.module.view",
    label: "View Equipment",
    description: "Access the Equipment Management module.",
    module: "equipment",
    group: "equipment_access",
  },
  {
    code: "equipment.record.create",
    label: "Add Equipment",
    description: "Add a new equipment record to the asset register.",
    module: "equipment",
    group: "equipment_actions",
  },
  {
    code: "equipment.record.edit",
    label: "Edit Equipment Record",
    description: "Edit equipment metadata and lifecycle information.",
    module: "equipment",
    group: "equipment_actions",
  },
  {
    code: "equipment.record.calibrate",
    label: "Manage Calibration",
    description: "Create and manage calibration records for equipment.",
    module: "equipment",
    group: "equipment_actions",
  },
  {
    code: "equipment.record.retire",
    label: "Retire Equipment",
    description: "Retire or decommission an equipment asset.",
    module: "equipment",
    group: "equipment_actions",
  },

  // ─── Supplier Management ─────────────────────────────────────────────────────
  {
    code: "supplier.module.view",
    label: "View Supplier Management",
    description: "Access the Supplier Management module.",
    module: "supplier",
    group: "supplier_access",
  },
  {
    code: "supplier.record.create",
    label: "Add Supplier",
    description: "Add a new supplier or vendor to the system.",
    module: "supplier",
    group: "supplier_actions",
  },
  {
    code: "supplier.record.edit",
    label: "Edit Supplier Record",
    description: "Edit supplier profile and qualification information.",
    module: "supplier",
    group: "supplier_actions",
  },
  {
    code: "supplier.record.approve",
    label: "Approve Supplier",
    description: "Approve or qualify a supplier for use.",
    module: "supplier",
    group: "supplier_actions",
  },
  {
    code: "supplier.record.audit",
    label: "Manage Supplier Audit",
    description: "Create and manage supplier audit records.",
    module: "supplier",
    group: "supplier_actions",
  },

  // ─── Product Management ──────────────────────────────────────────────────────
  {
    code: "product.module.view",
    label: "View Product Management",
    description: "Access the Product Management module.",
    module: "product",
    group: "product_access",
  },
  {
    code: "product.record.create",
    label: "Add Product",
    description: "Add a new product or specification to the system.",
    module: "product",
    group: "product_actions",
  },
  {
    code: "product.record.edit",
    label: "Edit Product Record",
    description: "Edit a product specification or lifecycle record.",
    module: "product",
    group: "product_actions",
  },

  // ─── Regulatory Management ───────────────────────────────────────────────────
  {
    code: "regulatory.module.view",
    label: "View Regulatory Management",
    description: "Access the Regulatory Management module.",
    module: "regulatory",
    group: "regulatory_access",
  },
  {
    code: "regulatory.record.create",
    label: "Create Regulatory Record",
    description: "Create a new regulatory record or submission.",
    module: "regulatory",
    group: "regulatory_actions",
  },
  {
    code: "regulatory.record.edit",
    label: "Edit Regulatory Record",
    description: "Edit an existing regulatory record.",
    module: "regulatory",
    group: "regulatory_actions",
  },
  {
    code: "regulatory.record.submit",
    label: "Submit Regulatory Filing",
    description: "Submit a regulatory filing or dossier to a health authority.",
    module: "regulatory",
    group: "regulatory_actions",
  },

  // ─── Reports & Analytics ─────────────────────────────────────────────────────
  {
    code: "report.module.view",
    label: "View Reports & Analytics",
    description: "Access reports, dashboards, and analytics workspaces.",
    module: "reports",
    group: "reports_access",
    legacyCodes: ["VIEW_REPORTS"],
  },
  {
    code: "report.module.export",
    label: "Export Reports",
    description: "Export reports and compliance data extracts.",
    module: "reports",
    group: "reports_access",
    legacyCodes: ["EXPORT_REPORTS"],
  },

  // ─── Audit Trail ─────────────────────────────────────────────────────────────
  {
    code: "audittrail.module.view",
    label: "View Audit Trail",
    description: "Access the system-wide audit trail module.",
    module: "audit-trail",
    group: "audit_trail_access",
    legacyCodes: ["VIEW_AUDIT_TRAIL"],
  },
  {
    code: "audit.export",
    label: "Export Audit Trail",
    description: "Export audit trail records for controlled review and inspection.",
    module: "audit-trail",
    group: "audit_trail_access",
    legacyCodes: ["audittrail.module.export", "VIEW_AUDIT_TRAIL"],
  },
  {
    code: "audit.review.view",
    label: "View Audit Trail Reviews",
    description: "View periodic audit-trail review campaigns, scope, and findings.",
    module: "audit-trail",
    group: "audit_review",
  },
  {
    code: "audit.review.manage",
    label: "Manage Audit Trail Reviews",
    description: "Create, perform, complete, and administer periodic audit-trail reviews.",
    module: "audit-trail",
    group: "audit_review",
  },

  // ─── System Administration ───────────────────────────────────────────────────
  {
    code: "settings.user.view",
    label: "View Users",
    description: "View user records and user-management lists.",
    module: "system-admin",
    group: "user_management",
    legacyCodes: ["VIEW_USERS"],
  },
  {
    code: "settings.user.create",
    label: "Create Users",
    description: "Create new user accounts.",
    module: "system-admin",
    group: "user_management",
    legacyCodes: ["CREATE_USERS"],
  },
  {
    code: "settings.user.edit",
    label: "Edit Users",
    description: "Edit user profiles, account details, and status.",
    module: "system-admin",
    group: "user_management",
    legacyCodes: ["EDIT_USERS"],
  },
  {
    code: "settings.user.delete",
    label: "Delete Users",
    description: "Delete or retire user accounts where policy allows.",
    module: "system-admin",
    group: "user_management",
    legacyCodes: ["DELETE_USERS"],
  },
  {
    code: "settings.user.reset_password",
    label: "Reset Passwords",
    description: "Reset other users' passwords.",
    module: "system-admin",
    group: "user_management",
    legacyCodes: ["RESET_PASSWORDS"],
  },
  {
    code: "settings.user.force_logout",
    label: "Force Logout Users",
    description: "Immediately terminate another user's active sessions.",
    module: "system-admin",
    group: "user_management",
  },
  {
    code: "users.invite_external",
    label: "Invite External Users",
    description: "Invite a user to Microsoft Entra as a guest without granting site-wide access.",
    module: "settings",
    group: "user_management",
  },
  {
    code: "users.resend_external_invitation",
    label: "Resend External Invitations",
    description: "Resend a pending Microsoft Entra guest invitation.",
    module: "settings",
    group: "user_management",
  },
  {
    code: "users.retry_external_provisioning",
    label: "Retry External Provisioning",
    description: "Retry a failed Microsoft Entra provisioning operation.",
    module: "settings",
    group: "user_management",
  },
  {
    code: "users.disable_microsoft_access",
    label: "Disable Microsoft Access",
    description: "Disable the provisioned Microsoft account without deleting the guest.",
    module: "settings",
    group: "user_management",
  },
  {
    code: "users.view_external_provisioning",
    label: "View External Provisioning",
    description: "View Microsoft Entra invitation status and provisioning errors.",
    module: "settings",
    group: "user_management",
  },
  {
    code: "security.permission_sets.view",
    label: "View Permission Sets",
    description: "View permission sets and their assigned permissions.",
    module: "security-authorization",
    group: "permission_sets",
  },
  {
    code: "security.permission_sets.update",
    label: "Manage Permission Sets",
    description: "Create, update, clone, deactivate, and assign permission sets.",
    module: "security-authorization",
    group: "permission_sets",
  },
  {
    code: "security.access_profiles.view",
    label: "View Access Profiles",
    description: "View access profiles, business roles, and assignment summaries.",
    module: "security-authorization",
    group: "access_profiles",
  },
  {
    code: "security.access_profiles.update",
    label: "Manage Access Profiles",
    description: "Create, update, deactivate, clone, and administer access profiles.",
    module: "security-authorization",
    group: "access_profiles",
  },
  {
    code: "security.access_profiles.assign",
    label: "Assign Access Profiles",
    description: "Assign users, permission sets, workflow roles, and object rules to access profiles.",
    module: "security-authorization",
    group: "access_profiles",
  },
  {
    code: "security.workflow_authorization.view",
    label: "View Workflow Authorization",
    description: "View workflow authorization policies and actor rules.",
    module: "security-authorization",
    group: "workflow_authorization",
  },
  {
    code: "security.workflow_authorization.manage",
    label: "Manage Workflow Authorization",
    description: "Create and update workflow authorization policies and actor rules.",
    module: "security-authorization",
    group: "workflow_authorization",
  },
  {
    code: "security.object_rules.view",
    label: "View Object Access Rules",
    description: "View object access rules and organization scope policies.",
    module: "security-authorization",
    group: "object_access",
  },
  {
    code: "security.object_rules.manage",
    label: "Manage Object Access Rules",
    description: "Create, update, deactivate, and delete object access rules.",
    module: "security-authorization",
    group: "object_access",
  },
  {
    code: "security.sod.view",
    label: "View Segregation of Duties",
    description: "View segregation-of-duties constraints and violation scans.",
    module: "security-authorization",
    group: "segregation_of_duties",
  },
  {
    code: "security.sod.manage",
    label: "Manage Segregation of Duties",
    description: "Create, update, and deactivate segregation-of-duties constraints.",
    module: "security-authorization",
    group: "segregation_of_duties",
  },

  // ─── Application Settings ────────────────────────────────────────────────────
  {
    code: "settings.configuration.view",
    label: "View Configuration",
    description: "View system configuration and maintenance settings.",
    module: "app-settings",
    group: "system_configuration",
    legacyCodes: ["VIEW_SETTINGS"],
  },
  {
    code: "settings.configuration.edit",
    label: "Edit Configuration",
    description: "Edit configuration, password policies, sessions, and maintenance settings.",
    module: "app-settings",
    group: "system_configuration",
    legacyCodes: ["EDIT_SETTINGS"],
  },
  {
    code: "settings.dictionary.view",
    label: "View Data Dictionaries",
    description: "View controlled dictionary values such as business units, departments, document types, and retention policies.",
    module: "app-settings",
    group: "data_dictionaries",
    legacyCodes: ["settings.configuration.view", "VIEW_SETTINGS"],
  },
  {
    code: "settings.dictionary.manage",
    label: "Manage Data Dictionaries",
    description: "Create, update, and delete controlled dictionary values used by GxP records.",
    module: "app-settings",
    group: "data_dictionaries",
    legacyCodes: ["settings.configuration.edit", "EDIT_SETTINGS"],
  },
  {
    code: "settings.controlled_copy_policy.view",
    label: "View Controlled Copies Policy",
    description: "View controlled copy distribution, expiry, recall, and security policy.",
    module: "app-settings",
    group: "document_control",
    legacyCodes: ["settings.configuration.view", "VIEW_SETTINGS"],
  },
  {
    code: "settings.controlled_copy_policy.manage",
    label: "Manage Controlled Copies Policy",
    description: "Update controlled copy distribution, expiry, recall, and security policy.",
    module: "app-settings",
    group: "document_control",
    legacyCodes: ["settings.configuration.edit", "EDIT_SETTINGS"],
  },
  {
    code: "settings.publishing_template.view",
    label: "View Publishing Templates",
    description: "View controlled publishing templates and their component previews.",
    module: "app-settings",
    group: "document_control",
  },
  {
    code: "settings.publishing_template.manage",
    label: "Manage Publishing Templates",
    description: "Create, update, activate, and retire controlled publishing templates.",
    module: "app-settings",
    group: "document_control",
  },
  {
    code: "settings.notification_policy.view",
    label: "View Notification Policy",
    description: "View system notification event, audience, delivery, and escalation policies.",
    module: "app-settings",
    group: "notification_policy",
  },
  {
    code: "settings.notification_policy.manage",
    label: "Manage Notification Policy",
    description: "Create and update system notification event, audience, delivery, and escalation policies.",
    module: "app-settings",
    group: "notification_policy",
  },

  // ─── Help & Support ──────────────────────────────────────────────────────────
  // ─── Preferences ─────────────────────────────────────────────────────────────
  {
    code: "preferences.module.view",
    label: "View Preferences",
    description: "Open the personal preferences area.",
    module: "preferences",
    group: "preferences_access",
  },
  {
    code: "preferences.module.edit",
    label: "Edit Preferences",
    description: "Edit personal preferences and self-service settings.",
    module: "preferences",
    group: "preferences_access",
  },
  {
    code: "audit.view",
    label: "View Audit Trail Records",
    description: "View the system-wide audit trail records.",
    module: "audit-trail",
    group: "audit_trail",
  },
  {
    code: "settings.configuration.manage",
    label: "Manage System Configuration",
    description: "Manage general system configuration.",
    module: "settings",
    group: "system_settings",
    legacyCodes: ["settings.configuration.edit", "EDIT_SETTINGS"],
  },
  {
    code: "settings.email_template.manage",
    label: "Manage Email Templates",
    description: "Create and edit notification email templates.",
    module: "settings",
    group: "system_settings",
    legacyCodes: ["settings.configuration.edit", "EDIT_SETTINGS"],
  },
  {
    code: "security.access_review.view",
    label: "View Access Reviews",
    description: "View periodic access-review campaigns and findings.",
    module: "security-authorization",
    group: "access_review",
  },
  {
    code: "security.access_review.manage",
    label: "Manage Access Reviews",
    description: "Create, decide, complete, and cancel access-review campaigns.",
    module: "security-authorization",
    group: "access_review",
  },
  {
    code: "security.maintenance.bypass",
    label: "Bypass Maintenance Mode",
    description: "Access the application while maintenance mode is active.",
    module: "security-authorization",
    group: "system_access",
  },

];

/**
 * Modules deferred from the current product scope are deliberately excluded
 * from the administration UI. The legacy descriptors remain only to preserve
 * compatibility with historical permission-set payloads until their database
 * records are removed by the decommission migration.
 */
const DEFERRED_MODULE_KEYS = new Set([
  "deviations",
  "capa",
  "change-control",
  "complaints",
  "risk-management",
  "equipment",
  "supplier",
  "product",
  "regulatory",
]);

export const SYSTEM_PERMISSION_CATALOG: PermissionDescriptor[] =
  LEGACY_PERMISSION_CATALOG.filter(
    (descriptor) => !DEFERRED_MODULE_KEYS.has(descriptor.module),
  );

const descriptorMap = new Map<string, PermissionDescriptor>();

SYSTEM_PERMISSION_CATALOG.forEach((descriptor) => {
  descriptorMap.set(descriptor.code.trim().toUpperCase(), descriptor);
});

export const findPermissionDescriptor = (code: string): PermissionDescriptor | null => {
  if (!code) return null;
  return descriptorMap.get(code.trim().toUpperCase()) ?? null;
};

export const resolvePermissionAliasCodes = (code: string): string[] => {
  // Authorization is deliberately exact and fail-closed. Historical aliases
  // remain descriptive migration metadata only and never grant runtime access.
  return [code];
};
