export interface PermissionDescriptor {
  code: string;
  label: string;
  description: string;
  module: string;
  group: string;
  legacyCodes?: string[];
}

const LEGACY_PERMISSION_CATALOG: PermissionDescriptor[] = [
  // ─── Notifications ──────────────────────────────────────────────────────────
  {
    code: "notifications.module.view",
    label: "View Notifications",
    description: "Access in-app notifications and alerts.",
    module: "notifications",
    group: "notifications_access",
  },
  {
    code: "notifications.recipient.qa_manager",
    label: "Receive QA Manager Notifications",
    description: "Receive notification-policy events addressed to the configured QA Manager audience.",
    module: "notifications",
    group: "notification_recipients",
  },

  // ─── Dashboard ──────────────────────────────────────────────────────────────
  {
    code: "dashboard.module.view",
    label: "View Dashboard",
    description: "Access the system dashboard and summary widgets.",
    module: "dashboard",
    group: "dashboard_access",
  },
  {
    code: "dashboard.admin.view",
    label: "View Administrative Dashboard",
    description: "View administrative dashboard statistics and security-oriented overview widgets.",
    module: "dashboard",
    group: "dashboard_admin",
  },

  // ─── Self-Service ───────────────────────────────────────────────────────────
  {
    code: "self_service.knowledge.view",
    label: "View Knowledge",
    description: "View the Knowledge portal under Self-Service (browse/search published documents, feedback, subscriptions).",
    module: "self_service",
    group: "self_service_access",
  },

  // ─── Document Control ───────────────────────────────────────────────────────
  {
    code: "documents.module.view",
    label: "View Document Control",
    description: "Access the Document Control module, including documents and revisions.",
    module: "documents",
    group: "document_control_access",
    legacyCodes: ["VIEW_DOCUMENTS"],
  },
  {
    code: "documents.document.view",
    label: "View Documents",
    description: "View documents and revisions permitted by the user's access scope.",
    module: "documents",
    group: "document_control_access",
  },
  {
    code: "documents.document.view_all",
    label: "View All Document Records",
    description: "View every document and revision, including records outside the user's business-unit scope. This permission is read-only.",
    module: "documents",
    group: "document_control_access",
  },
  {
    code: "documents.workspace.manage",
    label: "Manage Document Control Workspace",
    description: "Perform Document Control operational actions that are separately allowed by lifecycle and workflow policy. This does not grant authoring access to another user's Draft.",
    module: "documents",
    group: "document_control_access",
  },
  {
    code: "documents.document.configure_initial_workflow",
    label: "Configure Initial Document Workflow",
    description: "Select the initial reviewers, approvers, and document relationships while creating a new Document Master.",
    module: "documents",
    group: "document_authoring",
  },
  {
    code: "documents.revision.configure_next_reviewers",
    label: "Configure Next Revision Reviewers",
    description: "Change the reviewer routing inherited by the next revision of an Active document.",
    module: "documents",
    group: "document_authoring",
  },
  {
    code: "documents.revision.configure_next_approvers",
    label: "Configure Next Revision Approvers",
    description: "Change the approver routing inherited by the next revision of an Active document.",
    module: "documents",
    group: "document_authoring",
  },
  {
    code: "documents.revision.configure_next_related_documents",
    label: "Configure Next Revision Related Documents",
    description: "Change related documents inherited by the next revision of an Active document.",
    module: "documents",
    group: "document_authoring",
  },
  {
    code: "documents.revision.configure_next_correlated_documents",
    label: "Configure Next Revision Correlated Documents",
    description: "Change correlated documents inherited by the next revision of an Active document.",
    module: "documents",
    group: "document_authoring",
  },
  {
    code: "documents.document.create",
    label: "Create Document Shell",
    description: "Create a new document shell with metadata and workflow configuration.",
    module: "documents",
    group: "document_authoring",
    legacyCodes: ["CREATE_DOCUMENT_SHELL", "CREATE_DOCUMENTS"],
  },
  {
    code: "documents.document.edit_metadata",
    label: "Edit Document Metadata",
    description: "Update document metadata, ownership, and routing settings.",
    module: "documents",
    group: "document_authoring",
    legacyCodes: ["EDIT_DOCUMENT_METADATA", "EDIT_DOCUMENTS"],
  },
  {
    code: "documents.document.view_audit",
    label: "View Document Audit Trail",
    description:
      "View the Audit Trail tab for a document or revision. Direct stakeholders (Author, Co-author, Reviewer/Approver, Admin/DCO) see it automatically without this permission; it is only required for indirect/broad viewers.",
    module: "documents",
    group: "document_master",
    legacyCodes: ["VIEW_DOCUMENT_AUDIT_TRAIL", "VIEW_AUDIT_TRAIL"],
  },
  {
    code: "documents.document.reopen",
    label: "Reopen Cancelled Document",
    description: "Reopen a closed-cancelled Draft document with an auditable activity summary.",
    module: "documents",
    group: "document_master",
  },
  {
    code: "documents.document.update_metadata",
    label: "Update Draft Document Metadata",
    description: "Update metadata of a Draft document master.",
    module: "documents",
    group: "document_master",
  },
  {
    code: "documents.document.configure_next_metadata",
    label: "Configure Next Revision Metadata",
    description:
      "Change Author, Co-Author, Periodic Review Cycle/Notification, Review Date and Description inherited by the next revision of an Active document.",
    module: "documents",
    group: "revision_configuration",
  },
  {
    code: "documents.revision.update_draft_metadata",
    label: "Update Draft Revision Metadata",
    description: "Update metadata of a Draft document revision.",
    module: "documents",
    group: "document_control_access",
  },
  {
    code: "documents.revision.force_publish",
    label: "Force Publish Revision (Override Related Documents Check)",
    description:
      "Allows publishing a Revision even when one or more Related Documents are not currently Effective. GMP exception/deviation -- not granted by default.",
    module: "documents",
    group: "revision_workflow",
  },
  {
    code: "documents.controlled_copy.print",
    label: "Print Controlled Copy",
    description: "Print an authorized controlled copy.",
    module: "documents",
    group: "controlled_copy_files",
  },
  {
    code: "documents.controlled_copy.receive_as_dco",
    label: "Receive Controlled Copies as DCO",
    description:
      "Eligible to be selected in Controlled Copies Policy as the DCO recipient who receives the printable file/ZIP instead of the original requester(s) when delivery redirection is enabled.",
    module: "documents",
    group: "controlled_copy",
  },
  {
    code: "documents.document.obsolete",
    label: "Obsolete Document",
    description: "Obsolete an active document and its current lifecycle.",
    module: "documents",
    group: "document_lifecycle",
    legacyCodes: ["OBSOLETE_DOCUMENT"],
  },
  {
    code: "documents.document.cancel",
    label: "Cancel Document",
    description: "Cancel a document master lifecycle when its status allows it.",
    module: "documents",
    group: "document_lifecycle",
  },
  {
    code: "documents.document.preview_published",
    label: "Preview Published Document",
    description: "Open the controlled preview of a published document.",
    module: "documents",
    group: "document_access",
  },
  {
    code: "documents.revision.upload_source",
    label: "Upload Revision Source",
    description: "Upload or replace the controlled source file for an authorised Draft revision.",
    module: "documents",
    group: "revision_authoring",
    legacyCodes: ["UPLOAD_REVISION_FILE"],
  },
  {
    code: "documents.revision.submit_review",
    label: "Submit Revision for Review",
    description: "Submit a draft revision into the controlled workflow.",
    module: "documents",
    group: "revision_workflow",
    legacyCodes: ["SUBMIT_REVISION"],
  },
  {
    code: "documents.revision.review",
    label: "Review Revision",
    description: "Perform the assigned review step in a revision workflow.",
    module: "documents",
    group: "revision_workflow",
    legacyCodes: ["COMPLETE_REVIEW", "REVIEW_DOCUMENTS"],
  },
  {
    code: "documents.revision.approve",
    label: "Approve Revision",
    description: "Perform the assigned approval step in a revision workflow.",
    module: "documents",
    group: "revision_workflow",
    legacyCodes: ["APPROVE_REVISION", "APPROVE_DOCUMENTS"],
  },
  {
    code: "documents.revision.reject_review",
    label: "Reject Review",
    description: "Reject an assigned review and return the revision to authoring.",
    module: "documents",
    group: "revision_workflow",
    legacyCodes: ["REJECT_REVISION"],
  },
  {
    code: "documents.revision.reject_approval",
    label: "Reject Approval",
    description: "Reject an assigned approval and return the revision to the configured prior stage.",
    module: "documents",
    group: "revision_workflow",
  },
  {
    code: "documents.revision.complete_authoring",
    label: "Complete Authoring",
    description: "Complete authoring for a draft revision before it is submitted for review.",
    module: "documents",
    group: "revision_workflow",
  },
  {
    code: "documents.revision.open_publishing_workspace",
    label: "Open Publishing Workspace",
    description: "Open the publishing workspace for an authorised Ready for Publishing revision. Publishing remains a separate permission.",
    module: "documents",
    group: "revision_publish",
  },
  {
    code: "documents.revision.cancel",
    label: "Cancel Revision",
    description: "Cancel a revision while it is in an allowed in-progress lifecycle state.",
    module: "documents",
    group: "revision_workflow",
  },
  {
    code: "documents.revision.preview",
    label: "Preview Revision",
    description: "Preview revision content when the lifecycle and access policy allow it.",
    module: "documents",
    group: "revision_access",
  },
  {
    code: "documents.revision.edit_online",
    label: "Edit Revision Online",
    description: "Edit an authorized draft revision in the integrated online editor.",
    module: "documents",
    group: "revision_authoring",
  },
  {
    code: "documents.revision.upload_office_online",
    label: "Upload Revision to Office Online",
    description: "Upload or synchronize an authorised Draft revision working copy with Office Online.",
    module: "documents",
    group: "revision_authoring",
  },
  {
    code: "documents.revision.upgrade",
    label: "Upgrade Revision",
    description: "Create or upgrade a revision from an eligible document lifecycle state.",
    module: "documents",
    group: "revision_authoring",
  },
  {
    code: "documents.revision.publish",
    label: "Publish Revision",
    description: "Publish an approved revision and make it effective.",
    module: "documents",
    group: "revision_publish",
    legacyCodes: ["PUBLISH_REVISION", "PUBLISH_DOCUMENTS"],
  },
  {
    code: "documents.training.manage",
    label: "Manage Training Plan",
    description: "Manage training plan, effective distribution, and related assignments.",
    module: "documents",
    group: "training_publish",
    legacyCodes: ["MANAGE_TRAINING_PLAN"],
  },
  {
    code: "documents.training.complete",
    label: "Complete Training",
    description: "Complete assigned training steps for a document revision.",
    module: "documents",
    group: "training_publish",
    legacyCodes: ["COMPLETE_TRAINING"],
  },
  {
    code: "documents.controlled_copy.request",
    label: "Request Controlled Copy",
    description: "Request issuance or delivery of a controlled copy.",
    module: "documents",
    group: "controlled_copies",
    legacyCodes: ["REQUEST_CONTROLLED_COPY"],
  },
  {
    code: "documents.controlled_copy.distribute",
    label: "Distribute Controlled Copy",
    description: "Distribute a controlled copy batch that is ready for distribution.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.recall",
    label: "Recall Controlled Copy",
    description: "Recall a distributed controlled copy.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.cancel_request",
    label: "Cancel Controlled Copy Request",
    description: "Cancel an open controlled copy request.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.replace_lost_damaged",
    label: "Replace Lost or Damaged Copy",
    description: "Replace a controlled copy after a lost or damaged copy event.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.report_lost_damaged",
    label: "Report Lost or Damaged Copy",
    description: "Report that an issued controlled copy has been lost or damaged.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.expire",
    label: "Expire Controlled Copy",
    description: "Expire a controlled copy according to its lifecycle policy.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.view",
    label: "View Controlled Copy Records",
    description: "View controlled-copy requests, batches, recipients, and lifecycle status.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.view_file",
    label: "View Controlled Copy",
    description: "View a controlled copy file within the authorized access scope.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.download_file",
    label: "Download Controlled Copy",
    description: "Download a controlled copy file when download policy permits it.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.view_evidence",
    label: "View Controlled Copy Evidence",
    description: "View controlled copy distribution and acknowledgement evidence.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.download_evidence",
    label: "Download Controlled Copy Evidence",
    description: "Download controlled copy evidence when policy permits it.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.controlled_copy.upload_evidence",
    label: "Upload Controlled Copy Evidence",
    description: "Upload controlled-copy acknowledgement, return, or incident evidence.",
    module: "documents",
    group: "controlled_copies",
  },
  {
    code: "documents.admin.properties.view",
    label: "View Document Properties",
    description: "View the Document Properties screen (default revision number format, default document number format, file size limit, watermark and download policy).",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.properties.manage",
    label: "Manage Document Properties",
    description: "Edit the Document Properties screen (default revision number format, default document number format, file size limit, watermark and download policy).",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.name_formats.view",
    label: "View Document Name Formats",
    description: "View the Document Name Formats and Document Components catalogs.",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.name_formats.manage",
    label: "Manage Document Name Formats",
    description: "Create and edit Document Name Formats and Document Components.",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.document_types.view",
    label: "View Document Types",
    description: "View Document Types and Document Sub-Types.",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.document_types.manage",
    label: "Manage Document Types",
    description: "Create and edit Document Types and Document Sub-Types.",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.knowledge_categories.view",
    label: "View Knowledge Categories Hierarchies",
    description: "View the Knowledge Categories Hierarchies screen.",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.knowledge_categories.manage",
    label: "Manage Knowledge Categories Hierarchies",
    description: "Create and edit Knowledge Categories Hierarchies.",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.publishing_templates.view",
    label: "View Publishing Templates",
    description: "View Publishing Templates.",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.publishing_templates.manage",
    label: "Manage Publishing Templates",
    description: "Create and edit Publishing Templates.",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.controlled_copies_policy.view",
    label: "View Controlled Copies Policy",
    description: "View the Controlled Copies Policy screen (expiry limits, placeholder fields, distribution rules).",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.controlled_copies_policy.manage",
    label: "Manage Controlled Copies Policy",
    description: "Create and edit the Controlled Copies Policy (expiry limits, placeholder fields, distribution rules).",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.legacy_import.manage",
    label: "Legacy Import",
    description: "Import a document that already exists outside the system (e.g. a paper original) -- one revision or its entire historical revision chain (e.g. 1.0 through 4.0) -- assigning its existing document number and revision number(s) directly instead of the automatic sequence.",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.view",
    label: "View All Documents (Legacy Broad Grant)",
    description: "Grants blanket read access to every document master and revision system-wide. Also used as a fallback when viewing e-signature records and reviewing Controlled Copy batch distribution discrepancies.",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.manage",
    label: "Document Administration (Legacy, Superseded)",
    description: "No longer independently checked anywhere; superseded by the granular Document Administration permissions above. Kept only for historical Access Profile compatibility -- use the specific permissions instead.",
    module: "documents",
    group: "document_administration",
  },
  {
    code: "documents.admin.manage_workflow_roles",
    label: "Manage Document Revision Segregation-of-Duties Rules",
    description: "Edit the Document Revision workflow's segregation-of-duties rules (e.g. reviewer cannot approve, require two reviewers, author cannot review own revision). Unrelated to the Workflow Roles catalog under Security & Authorization.",
    module: "documents",
    group: "document_administration",
  },
  // ─── Training Management ─────────────────────────────────────────────────────
  {
    code: "training.module.view",
    label: "View Training",
    description: "Access the Training module and assigned training workflows.",
    module: "training",
    group: "training_access",
  },
  {
    code: "training.material.manage",
    label: "Manage Training Materials",
    description: "Create, update, review, and approve training materials and courses.",
    module: "training",
    group: "training_admin",
  },
  {
    code: "training.session.manage",
    label: "Manage Training Sessions",
    description: "Schedule and manage training sessions and attendance records.",
    module: "training",
    group: "training_admin",
  },
  {
    code: "training.assignment.manage",
    label: "Manage Training Assignments",
    description: "Assign training courses and requirements to users or groups.",
    module: "training",
    group: "training_admin",
  },
  {
    code: "training.admin.view",
    label: "View Training Administration",
    description: "View the Training Administration section under System Administration.",
    module: "training",
    group: "training_admin",
  },
  {
    code: "training.admin.properties.view",
    label: "View Training Properties",
    description: "View the Training Properties section under Training Administration.",
    module: "training",
    group: "training_admin",
  },
  {
    code: "training.admin.requirement_templates.view",
    label: "View Requirement Templates",
    description: "View the Requirement Templates section under Training Administration.",
    module: "training",
    group: "training_admin",
  },
  {
    code: "training.admin.quiz.view",
    label: "View Create a Quiz",
    description: "View the Create a Quiz section under Training Administration.",
    module: "training",
    group: "training_admin",
  },
  {
    code: "training.admin.curriculums.view",
    label: "View Curriculums",
    description: "View the Curriculums section under Training Administration.",
    module: "training",
    group: "training_admin",
  },


  // ─── Reports & Analytics ─────────────────────────────────────────────────────
  {
    code: "report.module.view",
    label: "View Reports & Analytics",
    description: "Access reports, dashboards, and analytics workspaces.",
    module: "reports",
    group: "reports_access",
    legacyCodes: ["VIEW_REPORTS"],
  },
  {
    code: "report.module.export",
    label: "Export Reports",
    description: "Export reports and compliance data extracts.",
    module: "reports",
    group: "reports_access",
    legacyCodes: ["EXPORT_REPORTS"],
  },

  // ─── Audit Trail ─────────────────────────────────────────────────────────────
  {
    code: "audittrail.module.view",
    label: "View Audit Trail",
    description: "Access the system-wide audit trail module.",
    module: "audit-trail",
    group: "audit_trail_access",
    legacyCodes: ["VIEW_AUDIT_TRAIL"],
  },
  {
    code: "audit.export",
    label: "Export Audit Trail",
    description: "Export audit trail records for controlled review and inspection.",
    module: "audit-trail",
    group: "audit_trail_access",
    legacyCodes: ["audittrail.module.export", "VIEW_AUDIT_TRAIL"],
  },
  {
    code: "audit.review.view",
    label: "View Audit Trail Reviews",
    description: "View periodic audit-trail review campaigns, scope, and findings.",
    module: "audit-trail",
    group: "audit_review",
  },
  {
    code: "audit.review.manage",
    label: "Manage Audit Trail Reviews",
    description: "Create, perform, complete, and administer periodic audit-trail reviews.",
    module: "audit-trail",
    group: "audit_review",
  },

  // ─── System Administration ───────────────────────────────────────────────────
  {
    code: "settings.user.view",
    label: "View Users",
    description: "View user records and user-management lists.",
    module: "system-admin",
    group: "user_management",
    legacyCodes: ["VIEW_USERS"],
  },
  {
    code: "settings.user.create",
    label: "Create Users",
    description: "Create new user accounts.",
    module: "system-admin",
    group: "user_management",
    legacyCodes: ["CREATE_USERS"],
  },
  {
    code: "settings.user.edit",
    label: "Edit Users",
    description: "Edit user profiles, account details, and status.",
    module: "system-admin",
    group: "user_management",
    legacyCodes: ["EDIT_USERS"],
  },
  {
    code: "settings.user.delete",
    label: "Delete Users",
    description: "Delete or retire user accounts where policy allows.",
    module: "system-admin",
    group: "user_management",
    legacyCodes: ["DELETE_USERS"],
  },
  {
    code: "settings.user.reset_password",
    label: "Reset Passwords",
    description: "Reset other users' passwords.",
    module: "system-admin",
    group: "user_management",
    legacyCodes: ["RESET_PASSWORDS"],
  },
  {
    code: "settings.user.force_logout",
    label: "Force Logout Users",
    description: "Immediately terminate another user's active sessions.",
    module: "system-admin",
    group: "user_management",
  },
  {
    code: "users.invite_external",
    label: "Invite External Users",
    description: "Invite a user to Microsoft Entra as a guest without granting site-wide access.",
    module: "settings",
    group: "user_management",
  },
  {
    code: "users.resend_external_invitation",
    label: "Resend External Invitations",
    description: "Resend a pending Microsoft Entra guest invitation.",
    module: "settings",
    group: "user_management",
  },
  {
    code: "users.retry_external_provisioning",
    label: "Retry External Provisioning",
    description: "Retry a failed Microsoft Entra provisioning operation.",
    module: "settings",
    group: "user_management",
  },
  {
    code: "users.disable_microsoft_access",
    label: "Disable Microsoft Access",
    description: "Disable the provisioned Microsoft account without deleting the guest.",
    module: "settings",
    group: "user_management",
  },
  {
    code: "users.view_external_provisioning",
    label: "View External Provisioning",
    description: "View Microsoft Entra invitation status and provisioning errors.",
    module: "settings",
    group: "user_management",
  },
  {
    code: "security.permission_sets.view",
    label: "View Permission Sets",
    description: "View permission sets and their assigned permissions.",
    module: "security-authorization",
    group: "permission_sets",
  },
  {
    code: "security.permission_sets.update",
    label: "Manage Permission Sets",
    description: "Create, update, clone, deactivate, and assign permission sets.",
    module: "security-authorization",
    group: "permission_sets",
  },
  {
    code: "security.access_profiles.view",
    label: "View Access Profiles",
    description: "View access profiles, business roles, and assignment summaries.",
    module: "security-authorization",
    group: "access_profiles",
  },
  {
    code: "security.access_profiles.update",
    label: "Manage Access Profiles",
    description: "Create, update, deactivate, clone, and administer access profiles.",
    module: "security-authorization",
    group: "access_profiles",
  },
  {
    code: "security.access_profiles.assign",
    label: "Assign Access Profiles",
    description: "Assign users, permission sets, workflow roles, and object rules to access profiles.",
    module: "security-authorization",
    group: "access_profiles",
  },
  {
    code: "security.workflow_authorization.view",
    label: "View Workflow Authorization",
    description: "View workflow authorization policies and actor rules.",
    module: "security-authorization",
    group: "workflow_authorization",
  },
  {
    code: "security.workflow_authorization.manage",
    label: "Manage Workflow Authorization",
    description: "Create and update workflow authorization policies and actor rules.",
    module: "security-authorization",
    group: "workflow_authorization",
  },
  {
    code: "security.object_rules.view",
    label: "View Object Access Rules",
    description: "View object access rules and organization scope policies.",
    module: "security-authorization",
    group: "object_access",
  },
  {
    code: "security.object_rules.manage",
    label: "Manage Object Access Rules",
    description: "Create, update, deactivate, and delete object access rules.",
    module: "security-authorization",
    group: "object_access",
  },
  {
    code: "security.sod.view",
    label: "View Segregation of Duties",
    description: "View segregation-of-duties constraints and violation scans.",
    module: "security-authorization",
    group: "segregation_of_duties",
  },
  {
    code: "security.sod.manage",
    label: "Manage Segregation of Duties",
    description: "Create, update, and deactivate segregation-of-duties constraints.",
    module: "security-authorization",
    group: "segregation_of_duties",
  },

  // ─── Application Settings ────────────────────────────────────────────────────
  {
    code: "settings.configuration.view",
    label: "View Configuration",
    description: "View system configuration and maintenance settings.",
    module: "app-settings",
    group: "system_configuration",
    legacyCodes: ["VIEW_SETTINGS"],
  },
  ...[
    ["business_unit", "Business Units"],
    ["department", "Departments"],
    ["position", "Positions"],
    ["storage_location", "Storage Locations"],
    ["retention_policy", "Retention Policies"],
    ["country", "Countries"],
    ["education.degree_level", "Education Degree Levels"],
    ["education.school", "Education Schools"],
  ].flatMap(([resource, label]) => [
    {
      code: `settings.${resource}.view`,
      label: `View ${label}`,
      description: `View controlled ${label.toLowerCase()} values.`,
      module: "app-settings",
      group: "data_dictionaries",
    },
    {
      code: `settings.${resource}.manage`,
      label: `Manage ${label}`,
      description: `Create, update, and delete controlled ${label.toLowerCase()} values.`,
      module: "app-settings",
      group: "data_dictionaries",
    },
  ]),
  {
    code: "settings.controlled_copy_policy.view",
    label: "View Controlled Copies Policy",
    description: "View controlled copy distribution, expiry, recall, and security policy.",
    module: "app-settings",
    group: "document_control",
    legacyCodes: ["settings.configuration.view", "VIEW_SETTINGS"],
  },
  {
    code: "settings.controlled_copy_policy.manage",
    label: "Manage Controlled Copies Policy",
    description: "Update controlled copy distribution, expiry, recall, and security policy.",
    module: "app-settings",
    group: "document_control",
    legacyCodes: ["settings.configuration.edit", "EDIT_SETTINGS"],
  },
  {
    code: "settings.publishing_template.view",
    label: "View Publishing Templates",
    description: "View controlled publishing templates and their component previews.",
    module: "app-settings",
    group: "document_control",
  },
  {
    code: "settings.publishing_template.manage",
    label: "Manage Publishing Templates",
    description: "Create, update, activate, and retire controlled publishing templates.",
    module: "app-settings",
    group: "document_control",
  },
  {
    code: "settings.notification_policy.view",
    label: "View Notification Policy",
    description: "View system notification event, audience, delivery, and escalation policies.",
    module: "app-settings",
    group: "notification_policy",
  },
  {
    code: "settings.notification_policy.manage",
    label: "Manage Notification Policy",
    description: "Create and update system notification event, audience, delivery, and escalation policies.",
    module: "app-settings",
    group: "notification_policy",
  },

  // ─── Help & Support ──────────────────────────────────────────────────────────
  // ─── Preferences ─────────────────────────────────────────────────────────────
  {
    code: "preferences.module.view",
    label: "View Preferences",
    description: "Open the personal preferences area.",
    module: "preferences",
    group: "preferences_access",
  },
  {
    code: "preferences.module.edit",
    label: "Edit Preferences",
    description: "Edit personal preferences and self-service settings.",
    module: "preferences",
    group: "preferences_access",
  },
  {
    code: "audit.view",
    label: "View Audit Trail Records",
    description: "View the system-wide audit trail records.",
    module: "audit-trail",
    group: "audit_trail",
  },
  {
    code: "settings.configuration.manage",
    label: "Manage System Configuration",
    description: "Manage general system configuration.",
    module: "settings",
    group: "system_settings",
    legacyCodes: ["settings.configuration.edit", "EDIT_SETTINGS"],
  },
  {
    code: "settings.email_template.view",
    label: "View Email Templates",
    description: "View notification email templates.",
    module: "settings",
    group: "system_settings",
  },
  {
    code: "settings.email_template.manage",
    label: "Manage Email Templates",
    description: "Create and edit notification email templates.",
    module: "settings",
    group: "system_settings",
    legacyCodes: ["settings.configuration.edit", "EDIT_SETTINGS"],
  },
  {
    code: "security.access_review.view",
    label: "View Access Reviews",
    description: "View periodic access-review campaigns and findings.",
    module: "security-authorization",
    group: "access_review",
  },
  {
    code: "security.access_review.manage",
    label: "Manage Access Reviews",
    description: "Create, decide, complete, and cancel access-review campaigns.",
    module: "security-authorization",
    group: "access_review",
  },
  {
    code: "security.maintenance.bypass",
    label: "Bypass Maintenance Mode",
    description: "Access the application while maintenance mode is active.",
    module: "security-authorization",
    group: "system_access",
  },

];

export const SYSTEM_PERMISSION_CATALOG: PermissionDescriptor[] = LEGACY_PERMISSION_CATALOG;

const descriptorMap = new Map<string, PermissionDescriptor>();

SYSTEM_PERMISSION_CATALOG.forEach((descriptor) => {
  descriptorMap.set(descriptor.code.trim().toUpperCase(), descriptor);
});

export const findPermissionDescriptor = (code: string): PermissionDescriptor | null => {
  if (!code) return null;
  return descriptorMap.get(code.trim().toUpperCase()) ?? null;
};

export const resolvePermissionAliasCodes = (code: string): string[] => {
  // Authorization is deliberately exact and fail-closed. Historical aliases
  // remain descriptive migration metadata only and never grant runtime access.
  return [code];
};
